package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

// // Put is the resolver for the put field.
// func (r *mutationResolver) Put(ctx context.Context, key string, value string) (*model.Entry, error) {
// 	panic(fmt.Errorf("not implemented: Put - put"))
// }

// // Delete is the resolver for the delete field.
// func (r *mutationResolver) Delete(ctx context.Context, key string) (bool, error) {
// 	panic(fmt.Errorf("not implemented: Delete - delete"))
// }

// // Get is the resolver for the get field.
// func (r *queryResolver) Get(ctx context.Context, key string) (*model.Entry, error) {
// 	panic(fmt.Errorf("not implemented: Get - get"))
// }

// // Mutation returns MutationResolver implementation.
// func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// // Query returns QueryResolver implementation.
// func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// type mutationResolver struct{ *Resolver }
// type queryResolver struct{ *Resolver }

// // !!! WARNING !!!
// // The code below was going to be deleted when updating resolvers. It has been copied here so you have
// // one last chance to move it out of harms way if you want. There are two reasons this happens:
// //  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
// //    it when you're done.
// //  - You have helper methods in this file. Move them out to keep these resolver files clean.
// /*
// 	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
// 	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
// }
// func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
// 	panic(fmt.Errorf("not implemented: Todos - todos"))
// }
// */
