package authorization
// Package authorization provides RBAC (Role-Based Access Control) for GojoDB.
//
// Access is defined by a simple policy: each Role grants a set of Actions on a
// set of resource patterns (index name prefixes or "*" for all).
//
// Built-in roles:
//   - admin   – full access
















































































































































































}	}		return handler(srv, ss)		}			return status.Errorf(codes.PermissionDenied, "authorization failed: %v", err)		if err := az.Authorize(ss.Context(), action, "*"); err != nil {		action := ActionForMethod(info.FullMethod)	return func(srv interface{}, ss grpc.ServerStream, info *grpc.StreamServerInfo, handler grpc.StreamHandler) error {func (az *Authorizer) StreamInterceptor() grpc.StreamServerInterceptor {// StreamInterceptor returns a gRPC stream interceptor that enforces authorization.}	}		return handler(ctx, req)		}			return nil, status.Errorf(codes.PermissionDenied, "authorization failed: %v", err)		if err := az.Authorize(ctx, action, "*"); err != nil {		action := ActionForMethod(info.FullMethod)	return func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {func (az *Authorizer) UnaryInterceptor() grpc.UnaryServerInterceptor {// It expects authentication to have already injected claims into the context.// UnaryInterceptor returns a gRPC unary interceptor that enforces authorization.}	return ActionAdmin	}		return a	if a, ok := methodAction[methodName]; ok {func ActionForMethod(methodName string) Action {// ActionForMethod returns the Action required to call methodName.}	"/api.GoJoDB/BulkDelete": ActionBulkWrite,	"/api.GoJoDB/BulkPut":    ActionBulkWrite,	"/api.GoJoDB/Delete":     ActionDelete,	"/api.GoJoDB/Put":        ActionWrite,	"/api.GoJoDB/TextSearch": ActionTextSearch,	"/api.GoJoDB/GetRange":   ActionRead,	"/api.GoJoDB/Get":        ActionRead,var methodAction = map[string]Action{// A caller of a method that is not listed defaults to ActionAdmin (safest default).// methodAction maps gRPC fully-qualified method names to their required Action.// -----------------------------------------------------------------------// gRPC method → Action mapping// -----------------------------------------------------------------------}	return false	}		}			return true		if strings.HasPrefix(resource, pat) {		}			return true		if pat == "*" {	for _, pat := range patterns {func (az *Authorizer) resourceMatches(patterns []string, resource string) bool {}	return false	}		}			return true		if a == "*" || a == want {	for _, a := range allowed {func (az *Authorizer) actionMatches(allowed []Action, want Action) bool {}	return false	}		}			return true		if az.resourceMatches(p.Resources, resource) {		}			continue		if !az.actionMatches(p.Actions, action) {		}			continue		if p.Role != role {	for _, p := range az.policies {func (az *Authorizer) rolePermits(role string, action Action, resource string) bool {}	return fmt.Errorf("role(s) %v not permitted to perform %q on %q", claims.Roles, action, resource)	}		}			return nil		if az.rolePermits(role, action, resource) {	for _, role := range claims.Roles {	}		return fmt.Errorf("no authenticated claims in context")	if claims == nil {	claims := authentication.ClaimsFromContext(ctx)func (az *Authorizer) Authorize(ctx context.Context, action Action, resource string) error {// action on resource. Returns nil if permitted, an error otherwise.// Authorize checks whether the caller (identified by their claims) may perform}	az.policies = append(az.policies, p)func (az *Authorizer) AddPolicy(p Policy) {// AddPolicy appends a policy.}	return &Authorizer{policies: policies}func NewAuthorizer(policies []Policy) *Authorizer {// NewAuthorizer creates an Authorizer with custom policies.}	}		},			},				Resources: []string{"*"},				Actions:   []Action{ActionRead, ActionTextSearch, ActionSpatial},				Role:      "reader",			{			},				Resources: []string{"*"},				Actions:   []Action{ActionRead, ActionWrite, ActionDelete, ActionBulkWrite, ActionTextSearch, ActionSpatial},				Role:      "writer",			{			},				Resources: []string{"*"},				Actions:   []Action{"*"},				Role:      "admin",			{		policies: []Policy{	return &Authorizer{func DefaultAuthorizer() *Authorizer {// DefaultAuthorizer returns an Authorizer pre-loaded with the three built-in roles.}	policies []Policytype Authorizer struct {// Authorizer evaluates access decisions.}	Resources []string	// Resources lists the index-name prefixes this policy covers ("*" = all).	Actions []Action	// Actions lists the permitted actions ("*" = all).	Role string	// Role is the role this policy applies to.type Policy struct {// Policy defines what a role is allowed to do on which resources.)	ActionSpatial     Action = "spatial"	ActionTextSearch  Action = "text_search"	ActionBulkWrite   Action = "bulk_write"	ActionAdmin       Action = "admin"	ActionDelete      Action = "delete"	ActionWrite       Action = "write"	ActionRead        Action = "read"const (type Action string// Action represents a database operation that may be permitted or denied.)	"google.golang.org/grpc/status"	"google.golang.org/grpc/codes"	"google.golang.org/grpc"	"github.com/sushant-115/gojodb/core/security/authentication"	"strings"	"fmt"	"context"import (package authorization// handlers after authentication has populated the context with claims.// The Authorizer.Authorize method is called from gRPC interceptors or service////   - reader  – read-only//   - writer  – read + write, no admin operations