# docker-compose.yml
# This file sets up a 3-node GojoDB cluster with a single gateway.
#
# To run:
# 1. Build the Docker images: docker-compose build
# 2. Start the cluster: docker-compose up -d
#
# To shutdown:
# docker-compose down

version: '3.8'

networks:
  gojodb-net:
    driver: bridge

services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC endpoint
    networks:
      - gojodb-net

  # --- GojoDB Storage Nodes ---
  # These are the core data storage and controller nodes.
  gojodb-server-1:
    image: gojodb-server
    build:
      context: .
      dockerfile: ./cmd/gojodb_server/Dockerfile
      args:
        COMPONENT_PATH: ./cmd/gojodb_server
    networks:
      - gojodb-net
    ports:
      - "8001:8001" # gRPC
      - "7001:7001" # Raft
      - "9001:9001" # HTTP
      - "6001:6001/udp" # Replication
      - "8083:8083" # Heartbeat
    volumes:
      - ./data/node1:/data
    command:
      - "/app/app"
      - "--node_id=node-1"
      - "--log_file=/tmp/node1"
      - "--grpc_addr=gojodb-server-1:8001"
      - "--raft_addr=gojodb-server-1:7001"
      - "--http_addr=gojodb-server-1:9001"
      - "--replication_addr=gojodb-server-1:6001"
      - "--heartbeat_addr=gojodb-server-1:8083"
      - "--controller_addr=gojodb-server-1:9001"
      - "--bootstrap"
      - "--oltp_endpoint=jaeger-all-in-one:4317"
      # First node, so no --join argument
    healthcheck:
      test: ["CMD", "sh", "-c", "sleep 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  gojodb-server-2:
    image: gojodb-server
    build:
      context: .
      dockerfile: ./cmd/gojodb_server/Dockerfile
      args:
        COMPONENT_PATH: ./cmd/gojodb_server
    networks:
      - gojodb-net
    ports:
      - "8002:8002"
      - "7002:7002"
      - "9002:9002"
      - "6002:6002/udp"
      - "8084:8084"
    volumes:
      - ./data/node2:/data
    command:
      - "/app/app"
      - "--node_id=node-2"
      - "--log_file=/tmp/node2"
      - "--grpc_addr=gojodb-server-2:8002"
      - "--raft_addr=gojodb-server-2:7002"
      - "--http_addr=gojodb-server-2:9002"
      - "--replication_addr=gojodb-server-2:6002"
      - "--heartbeat_addr=gojodb-server-2:8084"
      - "--controller_addr=gojodb-server-1:9001" # Join the cluster via node 1's Raft address
      - "--oltp_endpoint=jaeger-all-in-one:4317"
    depends_on:
      gojodb-server-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "sleep 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  gojodb-server-3:
    image: gojodb-server
    build:
      context: .
      dockerfile: ./cmd/gojodb_server/Dockerfile
      args:
        COMPONENT_PATH: ./cmd/gojodb_server
    networks:
      - gojodb-net
    ports:
      - "8003:8003"
      - "7003:7003"
      - "9003:9003"
      - "6003:6003/udp"
      - "8085:8085"
    volumes:
      - ./data/node3:/data
    command:
      - "/app/app"
      - "--node_id=node-3"
      - "--log_file=/tmp/node3"
      - "--grpc_addr=gojodb-server-3:8003"
      - "--raft_addr=gojodb-server-3:7003"
      - "--http_addr=gojodb-server-3:9003"
      - "--replication_addr=gojodb-server-3:6003"
      - "--heartbeat_addr=gojodb-server-3:8085"
      - "--controller_addr=gojodb-server-1:9001" # Join the cluster via node 1's Raft address
      - "--oltp_endpoint=jaeger-all-in-one:4317"
    depends_on:
      gojodb-server-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "sleep 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  # --- GojoDB Gateway ---
  # This is the single entry point for clients.

  gojodb-gateway:
    image: gojodb-gateway
    build:
      context: .
      dockerfile: ./cmd/gojodb_gateway/Dockerfile
      args:
        COMPONENT_PATH: ./cmd/gojodb_gateway
    networks:
      - gojodb-net
    ports:
      - "50051:50051" # Client-facing gRPC port
      - "9112:9112"
    environment:
      # The gateway needs to know the gRPC addresses of all storage nodes.
      - CLUSTER_NODES=gojodb-server-1:8001,gojodb-server-2:8002,gojodb-server-3:8003
      - LISTEN_ADDR=:7000
    command: ["/app/app", "--controller_addr=gojodb-server-1:9001", "--oltp_endpoint=jaeger-all-in-one:4317"]
    depends_on:
      gojodb-server-1:
        condition: service_healthy
      gojodb-server-2:
        condition: service_healthy
      gojodb-server-3:
        condition: service_healthy

volumes:
  node1-data:
  node2-data:
  node3-data:
