package authentication
// Package authentication provides JWT-based authentication for GojoDB's gRPC services.
//
// Tokens are signed with HMAC-SHA256 using a configurable secret key.
// A gRPC UnaryServerInterceptor and StreamServerInterceptor are provided so
// any service can bolt on authentication with a one-liner in its ServerOptions.
//
























































































































































































































func (w *wrappedStream) Context() context.Context { return w.ctx }}	ctx context.Context	grpc.ServerStreamtype wrappedStream struct {// wrappedStream wraps a grpc.ServerStream to override its context.}	return context.WithValue(ctx, claimsKey, claims), nil	}		return ctx, status.Errorf(codes.Unauthenticated, "invalid token: %v", err)	if err != nil {	claims, err := a.ValidateToken(token)	}		return ctx, status.Errorf(codes.Unauthenticated, "authentication required: %v", err)	if err != nil {	token, err := extractBearerToken(ctx)func (a *Authenticator) authenticate(ctx context.Context) (context.Context, error) {}	}		return handler(srv, &wrappedStream{ss, newCtx})		}			return err		if err != nil {		newCtx, err := a.authenticate(ss.Context())	return func(srv interface{}, ss grpc.ServerStream, info *grpc.StreamServerInfo, handler grpc.StreamHandler) error {func (a *Authenticator) StreamInterceptor() grpc.StreamServerInterceptor {// StreamInterceptor returns a gRPC stream server interceptor that enforces JWT authentication.}	}		return handler(newCtx, req)		}			return nil, err		if err != nil {		newCtx, err := a.authenticate(ctx)	return func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {func (a *Authenticator) UnaryInterceptor() grpc.UnaryServerInterceptor {// UnaryInterceptor returns a gRPC unary server interceptor that enforces JWT authentication.}	return strings.TrimSpace(auth[7:]), nil	}		return "", fmt.Errorf("authorization header must use Bearer scheme")	if !strings.HasPrefix(strings.ToLower(auth), "bearer ") {	auth := values[0]	}		return "", fmt.Errorf("authorization header missing")	if len(values) == 0 {	values := md.Get("authorization")	}		return "", fmt.Errorf("no metadata in request")	if !ok {	md, ok := metadata.FromIncomingContext(ctx)func extractBearerToken(ctx context.Context) (string, error) {// extractBearerToken retrieves the raw token from gRPC metadata.// -----------------------------------------------------------------------// gRPC interceptors// -----------------------------------------------------------------------}	return mac.Sum(nil)	mac.Write([]byte(input))	mac := hmac.New(sha256.New, a.secret)func (a *Authenticator) hmacSign(input string) []byte {}	return signingInput + "." + base64.RawURLEncoding.EncodeToString(sig), nil	sig := a.hmacSign(signingInput)	signingInput := header + "." + payload	payload := base64.RawURLEncoding.EncodeToString(payloadBytes)	}		return "", fmt.Errorf("failed to marshal claims: %w", err)	if err != nil {	payloadBytes, err := json.Marshal(claims)	header := base64.RawURLEncoding.EncodeToString([]byte(`{"alg":"HS256","typ":"JWT"}`))func (a *Authenticator) sign(claims *StandardClaims) (string, error) {// sign encodes and signs the claims, returning the compact JWT string.}	return &claims, nil	}		return nil, fmt.Errorf("token expired")	if claims.Expired() {	}		return nil, fmt.Errorf("invalid claims JSON: %w", err)	if err = json.Unmarshal(payloadBytes, &claims); err != nil {	var claims StandardClaims	}		return nil, fmt.Errorf("malformed payload: %w", err)	if err != nil {	payloadBytes, err := base64.RawURLEncoding.DecodeString(parts[1])	// Decode payload.	}		return nil, fmt.Errorf("invalid token signature")	if !hmac.Equal(sig, expected) {	expected := a.hmacSign(parts[0] + "." + parts[1])	}		return nil, fmt.Errorf("malformed signature: %w", err)	if err != nil {	sig, err := base64.RawURLEncoding.DecodeString(parts[2])	// Verify signature.	}		return nil, fmt.Errorf("malformed token: expected 3 parts, got %d", len(parts))	if len(parts) != 3 {	parts := strings.Split(token, ".")func (a *Authenticator) ValidateToken(token string) (*StandardClaims, error) {// ValidateToken parses and validates a token string, returning the claims.}	return a.sign(claims)	}		Issuer:    a.issuer,		ExpiresAt: now.Add(a.ttl).Unix(),		IssuedAt:  now.Unix(),		Roles:     roles,		Subject:   subject,	claims := &StandardClaims{	now := time.Now()func (a *Authenticator) IssueToken(subject string, roles []string) (string, error) {// IssueToken creates a signed JWT for the given subject and roles.}	return &Authenticator{secret: secret, issuer: issuer, ttl: ttl}, nil	}		ttl = 24 * time.Hour	if ttl == 0 {	}		return nil, fmt.Errorf("signing secret must be at least 32 bytes, got %d", len(secret))	if len(secret) < 32 {	}		}			return nil, fmt.Errorf("failed to generate signing key: %w", err)		if _, err := rand.Read(secret); err != nil {		secret = make([]byte, 32)	if len(secret) == 0 {func NewAuthenticator(secret []byte, issuer string, ttl time.Duration) (*Authenticator, error) {// (useful for tests — but not for production across restarts).// secret must be at least 32 bytes; if nil/empty a random 32-byte key is used// NewAuthenticator creates an Authenticator.}	ttl    time.Duration	issuer string	secret []byte // HMAC-SHA256 signing keytype Authenticator struct {// Authenticator signs and validates JWT tokens.// -----------------------------------------------------------------------// Authenticator – issues and validates tokens// -----------------------------------------------------------------------}	return c	c, _ := ctx.Value(claimsKey).(*StandardClaims)func ClaimsFromContext(ctx context.Context) *StandardClaims {// Returns nil if the context carries no authenticated claims.// ClaimsFromContext extracts validated claims from a context.}	return false	}		}			return true		if role == r {	for _, role := range c.Roles {func (c *StandardClaims) HasRole(r string) bool {// HasRole reports whether the subject has been granted role r.}	return time.Now().Unix() > c.ExpiresAtfunc (c *StandardClaims) Expired() bool {// Expired reports whether the token has passed its expiry time.}	Issuer    string   `json:"iss,omitempty"`	ExpiresAt int64    `json:"exp"`            // Unix seconds	IssuedAt  int64    `json:"iat"`            // Unix seconds	Roles     []string `json:"roles"`          // e.g. ["admin","reader"]	Subject   string   `json:"sub"`            // username / service accounttype StandardClaims struct {// StandardClaims is the JWT payload we issue and validate.const claimsKey contextKey = 0type contextKey int// contextKey is an unexported type used to store claims in a context.)	"google.golang.org/grpc/status"	"google.golang.org/grpc/metadata"	"google.golang.org/grpc/codes"	"google.golang.org/grpc"	"time"	"strings"	"fmt"	"encoding/json"	"encoding/base64"	"crypto/sha256"	"crypto/rand"	"crypto/hmac"	"context"import (package authentication// handlers and the authorization layer can read them without re-parsing.// The validated claims are injected into the request context so downstream