package kmsintegration
// Package kms_integration provides envelope encryption over the existing
// AES-GCM CryptoUtils layer.
//
// Envelope encryption works by generating a short-lived data-encryption key
// (DEK) in memory per operation; the DEK is then encrypted with a long-lived
// key-encryption key (KEK), and both the encrypted DEK and the ciphertext are


































































































































































































}	return p.defaultKey	defer p.mu.RUnlock()	p.mu.RLock()func (p *LocalKEKProvider) DefaultKeyID() string {// DefaultKeyID satisfies KEKProvider.}	return cp, nil	copy(cp, k)	cp := make([]byte, len(k))	// Return a copy so callers cannot mutate the stored key.	}		return nil, fmt.Errorf("kms: unknown key ID %q", keyID)	if !ok {	k, ok := p.keys[keyID]	defer p.mu.RUnlock()	p.mu.RLock()func (p *LocalKEKProvider) GetKEK(keyID string) ([]byte, error) {// GetKEK satisfies KEKProvider.}	return nil	p.defaultKey = keyID	}		return fmt.Errorf("kms: key %q not registered", keyID)	if _, ok := p.keys[keyID]; !ok {	defer p.mu.Unlock()	p.mu.Lock()func (p *LocalKEKProvider) SetDefaultKey(keyID string) error {// SetDefaultKey changes which key is used for new encryptions.}	return nil	p.keys[keyID] = key	defer p.mu.Unlock()	p.mu.Lock()	}		return fmt.Errorf("kms: KEK must be 16, 24, or 32 bytes; got %d", len(key))	if len(key) != 16 && len(key) != 24 && len(key) != 32 {func (p *LocalKEKProvider) AddKey(keyID string, key []byte) error {// AddKey adds a new KEK (for rotation; old key is retained for decryption).}	return p, nil	}		defaultKey: keyID,		keys:       map[string][]byte{keyID: primaryKey},	p := &LocalKEKProvider{	}		return nil, fmt.Errorf("kms: KEK must be 16, 24, or 32 bytes; got %d", len(primaryKey))	if len(primaryKey) != 16 && len(primaryKey) != 24 && len(primaryKey) != 32 {	}		}			return nil, fmt.Errorf("kms: generate KEK: %w", err)		if _, err := io.ReadFull(rand.Reader, primaryKey); err != nil {		primaryKey = make([]byte, 32)	if len(primaryKey) == 0 {func NewLocalKEKProvider(keyID string, primaryKey []byte) (*LocalKEKProvider, error) {// random 32-byte key is generated.// NewLocalKEKProvider creates a LocalKEKProvider.  If primaryKey is nil a}	defaultKey string	keys       map[string][]byte	mu         sync.RWMutextype LocalKEKProvider struct {// secrets manager, HSM, or cloud KMS.// LocalKEKProvider stores KEKs in memory.  In production, back this with a// ---------------------------------------------------------------------------// LocalKEKProvider — an in-process KEKProvider for development / testing.// ---------------------------------------------------------------------------}	return cu.Decrypt(payload.Ciphertext)	}		return nil, fmt.Errorf("kms: init data cipher for decrypt: %w", err)	if err != nil {	cu, err := encryption.NewCryptoUtils(dek)	// 3. Decrypt the data with the plaintext DEK.	}		return nil, fmt.Errorf("kms: unwrap DEK: %w", err)	if err != nil {	dek, err := kekCipher.Decrypt(payload.WrappedDEK)	// 2. Unwrap the DEK.	}		return nil, fmt.Errorf("kms: init key cipher for decrypt: %w", err)	if err != nil {	kekCipher, err := encryption.NewCryptoUtils(kekBytes)	}		return nil, fmt.Errorf("kms: get KEK %q: %w", payload.KeyID, err)	if err != nil {	kekBytes, err := e.kek.GetKEK(payload.KeyID)	// 1. Fetch the KEK that wrapped this DEK.func (e *EnvelopeEncryptor) Decrypt(payload *EnvelopePayload) ([]byte, error) {// uses the DEK to decrypt and return the original plaintext.// Decrypt unwraps the DEK using the KEK identified by payload.KeyID, then}	}, nil		Ciphertext: ciphertext,		WrappedDEK: wrappedDEK,		KeyID:      keyID,	return &EnvelopePayload{	}		return nil, fmt.Errorf("kms: wrap DEK: %w", err)	if err != nil {	wrappedDEK, err := kekCipher.Encrypt(dek)	}		return nil, fmt.Errorf("kms: init key cipher: %w", err)	if err != nil {	kekCipher, err := encryption.NewCryptoUtils(kekBytes)	}		return nil, fmt.Errorf("kms: get KEK %q: %w", keyID, err)	if err != nil {	kekBytes, err := e.kek.GetKEK(keyID)	keyID := e.kek.DefaultKeyID()	// 3. Wrap (encrypt) the DEK with the KEK.	}		return nil, fmt.Errorf("kms: encrypt data: %w", err)	if err != nil {	ciphertext, err := cu.Encrypt(plaintext)	}		return nil, fmt.Errorf("kms: init data cipher: %w", err)	if err != nil {	cu, err := encryption.NewCryptoUtils(dek)	// 2. Encrypt plaintext with the DEK using AES-GCM.	}		return nil, fmt.Errorf("kms: generate DEK: %w", err)	if _, err := io.ReadFull(rand.Reader, dek); err != nil {	dek := make([]byte, 32)	// 1. Generate a fresh 32-byte DEK.func (e *EnvelopeEncryptor) Encrypt(plaintext []byte) (*EnvelopePayload, error) {// wraps the DEK under the current KEK.  Returns an EnvelopePayload.// Encrypt generates a fresh random DEK, encrypts plaintext with it, and}	return &EnvelopeEncryptor{kek: kek}func NewEnvelopeEncryptor(kek KEKProvider) *EnvelopeEncryptor {// NewEnvelopeEncryptor creates an EnvelopeEncryptor using the given KEKProvider.}	mu  sync.Mutex // guards per-operation DEK ephemeral state	kek KEKProvidertype EnvelopeEncryptor struct {// KEKProvider to obtain key-encryption keys.// EnvelopeEncryptor performs envelope encryption / decryption using a}	DefaultKeyID() string	// DefaultKeyID returns the key ID that should be used for new encryptions.	GetKEK(keyID string) ([]byte, error)	// GetKEK returns the raw 32-byte KEK for the given keyID.type KEKProvider interface {// key store.// Implementations can delegate to AWS KMS, GCP Cloud KMS, Vault, or a local// KEKProvider is the contract for retrieving or generating key-encryption keys.}	Ciphertext []byte	// Ciphertext is the actual data encrypted with the plaintext DEK.	WrappedDEK []byte	// WrappedDEK is the DEK ciphertext (encrypted with the KEK).	KeyID string	// can be handled offline.	// KeyID identifies which KEK was used to wrap the DEK so that key rotationtype EnvelopePayload struct {// Both fields are binary-safe (raw bytes).// EnvelopePayload is the serialisable form of an encrypted value.)	"github.com/sushant-115/gojodb/core/security/encryption"	"sync"	"io"	"fmt"	"crypto/rand"import (package kms_integration// interface.// AWS KMS, GCP Cloud KMS, or HashiCorp Vault by satisfying the KEKProvider// deployment should replace NewLocalKEKProvider with a provider backed by// service, so it compiles and works without any network access.  A production// The implementation is self-contained and does NOT call an external KMS//// data: you only need to re-wrap the DEKs.// stored together.  This lets you rotate the KEK without re-encrypting all