// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Entry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type Query struct {
}
