package optimizer
// Package optimizer converts a parsed AST into a physical query plan,
// choosing the best index and access strategy for each statement.
//
// The optimizer follows a simple rule-based approach:
//   - EqPredicate / RangePredicate on "key" → B-tree index scan
//   - TextSearchPredicate → inverted-index scan
//   - NearPredicate / WithinPredicate → spatial R-tree scan


























































































































































































































































































}	return 1 - x2/2 + x2*x2/24 - x2*x2*x2/720	x2 := x * x	}		x += 2 * pi	for x < -pi {	}		x -= 2 * pi	for x > pi {	const pi = 3.14159265358979323846	// Clamp to [-π, π]func cosApprox(x float64) float64 {// cosApprox is a simple Taylor-series approximation (avoids importing math).}	return cosApprox(deg * pi / 180.0)	const pi = 3.14159265358979323846func cosDeg(deg float64) float64 {// cosDeg returns cos(degrees) for bounding-box calculations.}	}, nil		Child:      scanPlan,		WriteValue: s.Value,		IndexName:  s.IndexName,		Type:       PlanTypeUpdate,	return &Plan{	}		return nil, err	if err != nil {	scanPlan, _, err := buildScanPlan(s.IndexName, s.Where)	}		}, nil			WriteValue: s.Value,			WriteKey:   eq.Value,			IndexName:  s.IndexName,			Type:       PlanTypeUpdate,		return &Plan{	if eq, ok := s.Where.(*parser.EqPredicate); ok {func optimizeUpdate(s *parser.UpdateStmt) (*Plan, error) {}	return deletePlan, nil	}		deletePlan.Child = &Plan{Type: PlanTypeFilter, FilterPred: residual, Child: scanPlan}	if residual != nil {	}		Child:     scanPlan,		IndexName: s.IndexName,		Type:      PlanTypeDelete,	deletePlan := &Plan{	}		return nil, err	if err != nil {	scanPlan, residual, err := buildScanPlan(s.IndexName, s.Where)	// For non-equality deletes we need a scan + delete plan.	}		}, nil			WriteKey:  eq.Value,			IndexName: s.IndexName,			Type:      PlanTypeDelete,		return &Plan{	if eq, ok := s.Where.(*parser.EqPredicate); ok {func optimizeDelete(s *parser.DeleteStmt) (*Plan, error) {// -----------------------------------------------------------------------// DELETE / UPDATE optimisation// -----------------------------------------------------------------------}	plan.OrderAsc = !ob.Descfunc applySortHint(plan *Plan, ob *parser.OrderBy) {// applySortHint adjusts the scan direction / marks a sort is needed.}	}		}, pred, nil			OrderAsc:  true,			IndexName: indexName,			Type:      PlanTypeBtreeScan,		return &Plan{		// Fall back to full B-tree scan + filter.	default:		return leftPlan, p.Right, nil		}			return leftPlan, &parser.AndPredicate{Left: leftResidual, Right: p.Right}, nil		if leftResidual != nil {		// Left plan covers the index access; right becomes residual.		}			return leftPlan, p.Right, nil			// Both sides can use an index; just keep left plan + right as residual.		if rightErr == nil && leftResidual == nil {		_, _, rightErr := buildScanPlan(indexName, p.Right)		}			return nil, nil, err		if err != nil {		leftPlan, leftResidual, err := buildScanPlan(indexName, p.Left)		// Try to push one side to the index and keep the other as residual.	case *parser.AndPredicate:		}, nil, nil			OrderAsc:      true,			SpatialMaxLon: p.MaxLon,			SpatialMaxLat: p.MaxLat,			SpatialMinLon: p.MinLon,			SpatialMinLat: p.MinLat,			IndexName:     indexName,			Type:          PlanTypeSpatialScan,		return &Plan{	case *parser.WithinPredicate:		}, pred, nil // keep pred as residual for exact distance filtering			OrderAsc:      true,			SpatialMaxLon: p.Lon + lonDelta,			SpatialMaxLat: p.Lat + latDelta,			SpatialMinLon: p.Lon - lonDelta,			SpatialMinLat: p.Lat - latDelta,			IndexName:     indexName,			Type:          PlanTypeSpatialScan,		return &Plan{		lonDelta := p.Radius / (111000.0 * cosDeg(p.Lat))		latDelta := p.Radius / 111000.0		// Approximate: 1 degree lat ≈ 111 km, 1 degree lon ≈ 111 km * cos(lat).		// Build a bounding box around the NEAR circle for R-tree pre-filter.	case *parser.NearPredicate:		}, nil, nil			OrderAsc:  true,			TextQuery: p.Query,			TextField: p.Field,			IndexName: indexName,			Type:      PlanTypeInvertedScan,		return &Plan{		// Full-text search via inverted index.	case *parser.TextSearchPredicate:		}, nil, nil			OrderAsc:  true,			EndKey:    p.EndKey,			StartKey:  p.StartKey,			IndexName: indexName,			Type:      PlanTypeBtreeScan,		return &Plan{		// Range scan via B-tree.	case *parser.RangePredicate:		}, nil, nil			OrderAsc:  true,			PointKey:  p.Value,			IndexName: indexName,			Type:      PlanTypeBtreeScan,		return &Plan{		// Exact-match lookup via B-tree.	case *parser.EqPredicate:	switch p := pred.(type) {func buildScanPlan(indexName string, pred parser.Predicate) (*Plan, parser.Predicate, error) {// (scanPlan, residualPredicate).// buildScanPlan picks the best index access for a WHERE predicate and returns}	return root, nil	}		root.Limit = s.Limit	if s.Limit > 0 {	// LIMIT	}		applySortHint(root, s.OrderBy)	if s.OrderBy != nil {	// ORDER BY	}		root = &Plan{Type: PlanTypeFilter, FilterPred: residual, Child: root}	if residual != nil {	// Wrap with a residual Filter if the index couldn't absorb all predicates.	}		}			return nil, err		if err != nil {		root, residual, err = buildScanPlan(s.IndexName, s.Where)		var err error	} else {		}			OrderAsc:  true,			IndexName: s.IndexName,			Type:      PlanTypeBtreeScan,		root = &Plan{		// Full scan via B-tree (no predicate).	if s.Where == nil {	var residual parser.Predicate	var root *Planfunc optimizeSelect(s *parser.SelectStmt) (*Plan, error) {// -----------------------------------------------------------------------// SELECT optimisation// -----------------------------------------------------------------------}	}		return nil, fmt.Errorf("optimizer: unsupported statement type %T", stmt)	default:		return optimizeUpdate(s)	case *parser.UpdateStmt:		return optimizeDelete(s)	case *parser.DeleteStmt:		}, nil			WriteValue: s.Value,			WriteKey:   s.Key,			IndexName:  s.IndexName,			Type:       PlanTypeInsert,		return &Plan{	case *parser.InsertStmt:		return optimizeSelect(s)	case *parser.SelectStmt:	switch s := stmt.(type) {func Optimize(stmt parser.Statement) (*Plan, error) {// Optimize converts a parsed Statement into a physical Plan.}	Child *Plan	// Child plan for decorating nodes (Filter, Sort, Limit wrap a scan).	FilterPred parser.Predicate	// Predicate for Filter nodes (residual predicates the index can't handle).	OrderAsc bool // true = ascending (default)	Limit    int32	// Control	WriteValue string	WriteKey   string	// Write parameters (Insert/Delete/Update)	SpatialMaxLat, SpatialMaxLon float64	SpatialMinLat, SpatialMinLon float64	// SpatialScan parameters	TextField  string	TextQuery  string	// InvertedScan parameters	PointKey string // non-empty → exact-match lookup	EndKey   string // empty → point lookup	StartKey string	// BtreeScan parameters	IndexName string	Type      PlanTypetype Plan struct {// It forms a tree: each node may have a child that produces its input rows.// Plan is the physical execution plan for a single statement.)	PlanTypeLimit                        // Stop after N rows	PlanTypeSort                         // In-memory sort	PlanTypeFilter                       // Post-scan predicate filter	PlanTypeUpdate                       // Overwrite a value	PlanTypeDelete                       // Delete a key	PlanTypeInsert                       // Write a single key-value pair	PlanTypeSpatialScan                  // Geo query via R-tree	PlanTypeInvertedScan                 // Full-text search via inverted index	PlanTypeBtreeScan    PlanType = iota // Point or range lookup via B-treeconst (type PlanType int// PlanType identifies the physical operation a plan node performs.)	"github.com/sushant-115/gojodb/core/query_engine/parser"	"fmt"import (package optimizer// A cost-based layer can be added later once statistics are collected.////   - No predicate → full B-tree scan