package backup
// Package backup provides full-snapshot and incremental (WAL-delta) backup
// utilities for GojoDB storage nodes.
//
// A Backup consists of:
//  1. A snapshot of every registered IndexManager (serialised to a temp dir).
//  2. The WAL tail from the snapshot LSN up to the moment the backup completes.
//
// Backups can be written to local disk or to an object-storage prefix
























































































































































































}	return pr	}()		pw.Close()		_, _ = pw.Write(b)	go func() {	pr, pw := io.Pipe()	// Use an anonymous pipe for simplicity.	type bytesReader struct{ *os.File }func newBytesReader(b []byte) io.Reader {// newBytesReader wraps a byte slice as an io.Reader.}	return manifest, nil		zap.Duration("elapsed", manifest.CompletedAt.Sub(manifest.StartedAt)))		zap.String("backupID", backupID),	m.logger.Info("full backup completed",	manifest.Files = append(manifest.Files, manifestPath)	manifest.CompletedAt = time.Now()	}		return nil, fmt.Errorf("backup: writing manifest: %w", err)	if err = m.sink.Write(ctx, manifestPath, manifestReader); err != nil {	manifestReader := newBytesReader(manifestBytes)	manifestPath := filepath.Join(backupID, "manifest.json")	_ = import_io // ensure io is referenced	import_io := io.NopCloser	}		return nil, fmt.Errorf("backup: marshal manifest: %w", err)	if err != nil {	manifestBytes, err := json.MarshalIndent(manifest, "", "  ")	// Serialise and write the manifest.	}		m.logger.Info("snapshot written", zap.String("manager", s.Name()), zap.String("file", filePath))		manifest.Files = append(manifest.Files, filePath)		}			return nil, fmt.Errorf("backup: streaming snapshot for %s: %w", s.Name(), err)		if err := <-errCh; err != nil {		}			return nil, fmt.Errorf("backup: writing snapshot for %s: %w", s.Name(), err)		if err := m.sink.Write(ctx, filePath, pr); err != nil {		filePath := filepath.Join(backupID, "snapshots", s.Name()+".snap")		}()			}				}					return				if _, writeErr := pw.Write(chunk); writeErr != nil {			for chunk := range chunkCh {			defer pw.Close()		go func() {		pr, pw := io.Pipe()		// Pipe chunks to the sink via an in-memory reader.		}(s, snapshotID, chunkCh)			errCh <- streamer.StreamSnapshot(ctx, sid, ch)		go func(streamer Snapshotter, sid string, ch chan []byte) {		errCh := make(chan error, 1)		chunkCh := make(chan []byte, 64)		manifest.SnapshotLSN[s.Name()] = s.GetLatestLSN()		}			return nil, fmt.Errorf("backup: PrepareSnapshot for %s failed: %w", s.Name(), err)		if err != nil {		snapshotID, err := s.PrepareSnapshot(ctx)	for _, s := range m.snapshotters {	m.logger.Info("starting full backup", zap.String("backupID", backupID))	}		SnapshotLSN: make(map[string]uint64),		StartedAt:   time.Now(),		NodeID:      m.nodeID,		BackupID:    backupID,	manifest := &Manifest{	backupID := fmt.Sprintf("backup-%s-%d", m.nodeID, time.Now().UnixNano())	}()		m.mu.Unlock()		m.inProgress = false		m.mu.Lock()	defer func() {	m.mu.Unlock()	m.inProgress = true	}		return nil, fmt.Errorf("backup already in progress")		m.mu.Unlock()	if m.inProgress {	m.mu.Lock()func (m *Manager) RunFullBackup(ctx context.Context) (*Manifest, error) {// Returns the Manifest describing what was written.// RunFullBackup takes a full snapshot of all index managers and writes it to the sink.}	}		sink:         sink,		snapshotters: snapshotters,		nodeID:       nodeID,		logger:       logger.Named("backup"),	return &Manager{func NewManager(logger *zap.Logger, nodeID string, snapshotters []Snapshotter, sink Sink) *Manager {// NewManager creates a backup Manager.}	inProgress   bool	mu           sync.Mutex	sink         Sink	snapshotters []Snapshotter	nodeID       string	logger       *zap.Loggertype Manager struct {// Manager orchestrates backups across all registered index managers.}	Files       []string          `json:"files"`	SnapshotLSN map[string]uint64 `json:"snapshot_lsn"` // manager name → LSN	CompletedAt time.Time         `json:"completed_at"`	StartedAt   time.Time         `json:"started_at"`	NodeID      string            `json:"node_id"`	BackupID    string            `json:"backup_id"`type Manifest struct {// Manifest describes a completed backup.}	return err	_, err = io.Copy(f, r)	defer f.Close()	}		return err	if err != nil {	f, err := os.Create(fullPath) // #nosec G304 – path is constructed internally	}		return err	if err := os.MkdirAll(filepath.Dir(fullPath), 0750); err != nil {	fullPath := filepath.Join(ls.BaseDir, path)func (ls *LocalSink) Write(ctx context.Context, path string, r io.Reader) error {// Write implements Sink for local filesystem.}	BaseDir stringtype LocalSink struct {// LocalSink writes backups to a local directory.}	Write(ctx context.Context, path string, r io.Reader) error	// Write uploads/writes data to the sink under the given path.type Sink interface {// Implementations may be local-filesystem, S3, GCS, etc.// Sink is a writable destination for backup data.}	GetLatestLSN() uint64	// GetLatestLSN returns the LSN at the point the snapshot was prepared.	StreamSnapshot(ctx context.Context, snapshotID string, ch chan []byte) error	// StreamSnapshot streams the snapshot data chunk-by-chunk.	PrepareSnapshot(ctx context.Context) (string, error)	// PrepareSnapshot prepares a snapshot and returns a snapshot ID.	Name() string	// Name returns a unique identifier for this manager (used as filename prefix).type Snapshotter interface {// Snapshotter is implemented by any index manager that can produce a snapshot.)	"go.uber.org/zap"	"time"	"sync"	"path/filepath"	"os"	"io"	"fmt"	"encoding/json"	"context"import (package backup// (S3/GCS) when a BackupSink is provided.