// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      string                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        string                 `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRangeRequest) Reset() {
	*x = GetRangeRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRangeRequest) ProtoMessage() {}

func (x *GetRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRangeRequest.ProtoReflect.Descriptor instead.
func (*GetRangeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetRangeRequest) GetStartKey() string {
	if x != nil {
		return x.StartKey
	}
	return ""
}

func (x *GetRangeRequest) GetEndKey() string {
	if x != nil {
		return x.EndKey
	}
	return ""
}

func (x *GetRangeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type KeyValuePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*KeyValuePair        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRangeResponse) Reset() {
	*x = GetRangeResponse{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRangeResponse) ProtoMessage() {}

func (x *GetRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRangeResponse.ProtoReflect.Descriptor instead.
func (*GetRangeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetRangeResponse) GetEntries() []*KeyValuePair {
	if x != nil {
		return x.Entries
	}
	return nil
}

type TextSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	IndexName     string                 `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextSearchRequest) Reset() {
	*x = TextSearchRequest{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSearchRequest) ProtoMessage() {}

func (x *TextSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextSearchRequest.ProtoReflect.Descriptor instead.
func (*TextSearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *TextSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TextSearchRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *TextSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TextSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextSearchResult) Reset() {
	*x = TextSearchResult{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSearchResult) ProtoMessage() {}

func (x *TextSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextSearchResult.ProtoReflect.Descriptor instead.
func (*TextSearchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *TextSearchResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TextSearchResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type TextSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TextSearchResult    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextSearchResponse) Reset() {
	*x = TextSearchResponse{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSearchResponse) ProtoMessage() {}

func (x *TextSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextSearchResponse.ProtoReflect.Descriptor instead.
func (*TextSearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *TextSearchResponse) GetResults() []*TextSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type BulkPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*KeyValuePair        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkPutRequest) Reset() {
	*x = BulkPutRequest{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkPutRequest) ProtoMessage() {}

func (x *BulkPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkPutRequest.ProtoReflect.Descriptor instead.
func (*BulkPutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *BulkPutRequest) GetEntries() []*KeyValuePair {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BulkPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkPutResponse) Reset() {
	*x = BulkPutResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkPutResponse) ProtoMessage() {}

func (x *BulkPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkPutResponse.ProtoReflect.Descriptor instead.
func (*BulkPutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *BulkPutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BulkPutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BulkDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkDeleteRequest) Reset() {
	*x = BulkDeleteRequest{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkDeleteRequest) ProtoMessage() {}

func (x *BulkDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkDeleteRequest.ProtoReflect.Descriptor instead.
func (*BulkDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *BulkDeleteRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type BulkDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkDeleteResponse) Reset() {
	*x = BulkDeleteResponse{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkDeleteResponse) ProtoMessage() {}

func (x *BulkDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkDeleteResponse.ProtoReflect.Descriptor instead.
func (*BulkDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *BulkDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BulkDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StorageNode defines a storage node in the cluster
type StorageNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // gRPC address (host:port) for data operations
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`   // e.g., "active", "down", "onboarding", "migrating"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageNode) Reset() {
	*x = StorageNode{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageNode) ProtoMessage() {}

func (x *StorageNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageNode.ProtoReflect.Descriptor instead.
func (*StorageNode) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *StorageNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StorageNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *StorageNode) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// AddStorageNodeRequest requests to register a new storage node.
// This doesn't actually start the node, but informs the controller of its expected presence.
type AddStorageNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // Address where the storage node will be listening
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStorageNodeRequest) Reset() {
	*x = AddStorageNodeRequest{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStorageNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStorageNodeRequest) ProtoMessage() {}

func (x *AddStorageNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStorageNodeRequest.ProtoReflect.Descriptor instead.
func (*AddStorageNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *AddStorageNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AddStorageNodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AddStorageNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStorageNodeResponse) Reset() {
	*x = AddStorageNodeResponse{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStorageNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStorageNodeResponse) ProtoMessage() {}

func (x *AddStorageNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStorageNodeResponse.ProtoReflect.Descriptor instead.
func (*AddStorageNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *AddStorageNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddStorageNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RemoveStorageNodeRequest requests to remove a storage node.
type RemoveStorageNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStorageNodeRequest) Reset() {
	*x = RemoveStorageNodeRequest{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStorageNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStorageNodeRequest) ProtoMessage() {}

func (x *RemoveStorageNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStorageNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveStorageNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveStorageNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RemoveStorageNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStorageNodeResponse) Reset() {
	*x = RemoveStorageNodeResponse{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStorageNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStorageNodeResponse) ProtoMessage() {}

func (x *RemoveStorageNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStorageNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveStorageNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveStorageNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveStorageNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ShardSlotAssignment represents a shard slot's primary and replicas.
type ShardSlotAssignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SlotId         uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	PrimaryNodeId  string                 `protobuf:"bytes,2,opt,name=primary_node_id,json=primaryNodeId,proto3" json:"primary_node_id,omitempty"`
	ReplicaNodeIds []string               `protobuf:"bytes,3,rep,name=replica_node_ids,json=replicaNodeIds,proto3" json:"replica_node_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShardSlotAssignment) Reset() {
	*x = ShardSlotAssignment{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardSlotAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardSlotAssignment) ProtoMessage() {}

func (x *ShardSlotAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardSlotAssignment.ProtoReflect.Descriptor instead.
func (*ShardSlotAssignment) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

func (x *ShardSlotAssignment) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *ShardSlotAssignment) GetPrimaryNodeId() string {
	if x != nil {
		return x.PrimaryNodeId
	}
	return ""
}

func (x *ShardSlotAssignment) GetReplicaNodeIds() []string {
	if x != nil {
		return x.ReplicaNodeIds
	}
	return nil
}

// AssignShardSlotRequest requests to assign a slot to a primary and replicas.
type AssignShardSlotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SlotId         uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	PrimaryNodeId  string                 `protobuf:"bytes,2,opt,name=primary_node_id,json=primaryNodeId,proto3" json:"primary_node_id,omitempty"`
	ReplicaNodeIds []string               `protobuf:"bytes,3,rep,name=replica_node_ids,json=replicaNodeIds,proto3" json:"replica_node_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignShardSlotRequest) Reset() {
	*x = AssignShardSlotRequest{}
	mi := &file_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignShardSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignShardSlotRequest) ProtoMessage() {}

func (x *AssignShardSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignShardSlotRequest.ProtoReflect.Descriptor instead.
func (*AssignShardSlotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

func (x *AssignShardSlotRequest) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *AssignShardSlotRequest) GetPrimaryNodeId() string {
	if x != nil {
		return x.PrimaryNodeId
	}
	return ""
}

func (x *AssignShardSlotRequest) GetReplicaNodeIds() []string {
	if x != nil {
		return x.ReplicaNodeIds
	}
	return nil
}

type AssignShardSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignShardSlotResponse) Reset() {
	*x = AssignShardSlotResponse{}
	mi := &file_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignShardSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignShardSlotResponse) ProtoMessage() {}

func (x *AssignShardSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignShardSlotResponse.ProtoReflect.Descriptor instead.
func (*AssignShardSlotResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{23}
}

func (x *AssignShardSlotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignShardSlotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// InitiateReplicaOnboardingRequest initiates a new replica's onboarding process.
type InitiateReplicaOnboardingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SlotId         uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	ReplicaNodeId  string                 `protobuf:"bytes,2,opt,name=replica_node_id,json=replicaNodeId,proto3" json:"replica_node_id,omitempty"`  // The node joining as a replica
	PrimaryNodeId  string                 `protobuf:"bytes,3,opt,name=primary_node_id,json=primaryNodeId,proto3" json:"primary_node_id,omitempty"`  // The current primary to snapshot from
	ReplicaAddress string                 `protobuf:"bytes,4,opt,name=replica_address,json=replicaAddress,proto3" json:"replica_address,omitempty"` // gRPC address of the replica for snapshot streaming
	PrimaryAddress string                 `protobuf:"bytes,5,opt,name=primary_address,json=primaryAddress,proto3" json:"primary_address,omitempty"` // gRPC address of the primary for snapshot streaming
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitiateReplicaOnboardingRequest) Reset() {
	*x = InitiateReplicaOnboardingRequest{}
	mi := &file_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateReplicaOnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateReplicaOnboardingRequest) ProtoMessage() {}

func (x *InitiateReplicaOnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateReplicaOnboardingRequest.ProtoReflect.Descriptor instead.
func (*InitiateReplicaOnboardingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{24}
}

func (x *InitiateReplicaOnboardingRequest) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *InitiateReplicaOnboardingRequest) GetReplicaNodeId() string {
	if x != nil {
		return x.ReplicaNodeId
	}
	return ""
}

func (x *InitiateReplicaOnboardingRequest) GetPrimaryNodeId() string {
	if x != nil {
		return x.PrimaryNodeId
	}
	return ""
}

func (x *InitiateReplicaOnboardingRequest) GetReplicaAddress() string {
	if x != nil {
		return x.ReplicaAddress
	}
	return ""
}

func (x *InitiateReplicaOnboardingRequest) GetPrimaryAddress() string {
	if x != nil {
		return x.PrimaryAddress
	}
	return ""
}

type InitiateReplicaOnboardingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	OnboardingId  string                 `protobuf:"bytes,3,opt,name=onboarding_id,json=onboardingId,proto3" json:"onboarding_id,omitempty"` // Unique ID for tracking this onboarding process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateReplicaOnboardingResponse) Reset() {
	*x = InitiateReplicaOnboardingResponse{}
	mi := &file_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateReplicaOnboardingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateReplicaOnboardingResponse) ProtoMessage() {}

func (x *InitiateReplicaOnboardingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateReplicaOnboardingResponse.ProtoReflect.Descriptor instead.
func (*InitiateReplicaOnboardingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{25}
}

func (x *InitiateReplicaOnboardingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitiateReplicaOnboardingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitiateReplicaOnboardingResponse) GetOnboardingId() string {
	if x != nil {
		return x.OnboardingId
	}
	return ""
}

// UpdateReplicaOnboardingStateRequest updates the state of an ongoing replica onboarding.
type UpdateReplicaOnboardingStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnboardingId  string                 `protobuf:"bytes,1,opt,name=onboarding_id,json=onboardingId,proto3" json:"onboarding_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                            // e.g., "in_progress", "snapshot_complete", "log_catchup", "completed", "failed"
	CurrentLsn    uint64                 `protobuf:"varint,3,opt,name=current_lsn,json=currentLsn,proto3" json:"current_lsn,omitempty"` // Last Sequence Number processed by replica
	TargetLsn     uint64                 `protobuf:"varint,4,opt,name=target_lsn,json=targetLsn,proto3" json:"target_lsn,omitempty"`    // Target LSN on primary at initiation
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReplicaOnboardingStateRequest) Reset() {
	*x = UpdateReplicaOnboardingStateRequest{}
	mi := &file_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReplicaOnboardingStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplicaOnboardingStateRequest) ProtoMessage() {}

func (x *UpdateReplicaOnboardingStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplicaOnboardingStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateReplicaOnboardingStateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateReplicaOnboardingStateRequest) GetOnboardingId() string {
	if x != nil {
		return x.OnboardingId
	}
	return ""
}

func (x *UpdateReplicaOnboardingStateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateReplicaOnboardingStateRequest) GetCurrentLsn() uint64 {
	if x != nil {
		return x.CurrentLsn
	}
	return 0
}

func (x *UpdateReplicaOnboardingStateRequest) GetTargetLsn() uint64 {
	if x != nil {
		return x.TargetLsn
	}
	return 0
}

func (x *UpdateReplicaOnboardingStateRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateReplicaOnboardingStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReplicaOnboardingStateResponse) Reset() {
	*x = UpdateReplicaOnboardingStateResponse{}
	mi := &file_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReplicaOnboardingStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReplicaOnboardingStateResponse) ProtoMessage() {}

func (x *UpdateReplicaOnboardingStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReplicaOnboardingStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateReplicaOnboardingStateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateReplicaOnboardingStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateReplicaOnboardingStateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// InitiateShardMigrationRequest initiates data migration for a shard.
type InitiateShardMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	SourceNodeId  string                 `protobuf:"bytes,2,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`  // Current primary/replica holding the data
	TargetNodeId  string                 `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`  // New primary/replica to migrate data to
	SourceAddress string                 `protobuf:"bytes,4,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"` // gRPC address of the source node
	TargetAddress string                 `protobuf:"bytes,5,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"` // gRPC address of the target node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateShardMigrationRequest) Reset() {
	*x = InitiateShardMigrationRequest{}
	mi := &file_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateShardMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateShardMigrationRequest) ProtoMessage() {}

func (x *InitiateShardMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateShardMigrationRequest.ProtoReflect.Descriptor instead.
func (*InitiateShardMigrationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{28}
}

func (x *InitiateShardMigrationRequest) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *InitiateShardMigrationRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *InitiateShardMigrationRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *InitiateShardMigrationRequest) GetSourceAddress() string {
	if x != nil {
		return x.SourceAddress
	}
	return ""
}

func (x *InitiateShardMigrationRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

type InitiateShardMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MigrationId   string                 `protobuf:"bytes,3,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"` // Unique ID for tracking this migration process
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateShardMigrationResponse) Reset() {
	*x = InitiateShardMigrationResponse{}
	mi := &file_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateShardMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateShardMigrationResponse) ProtoMessage() {}

func (x *InitiateShardMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateShardMigrationResponse.ProtoReflect.Descriptor instead.
func (*InitiateShardMigrationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{29}
}

func (x *InitiateShardMigrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitiateShardMigrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitiateShardMigrationResponse) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

// CommitShardMigrationRequest commits a pending shard migration.
type CommitShardMigrationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SlotId            uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	NewPrimaryNodeId  string                 `protobuf:"bytes,2,opt,name=new_primary_node_id,json=newPrimaryNodeId,proto3" json:"new_primary_node_id,omitempty"`    // The node that will become the new primary
	NewReplicaNodeIds []string               `protobuf:"bytes,3,rep,name=new_replica_node_ids,json=newReplicaNodeIds,proto3" json:"new_replica_node_ids,omitempty"` // Optional: new set of replicas
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommitShardMigrationRequest) Reset() {
	*x = CommitShardMigrationRequest{}
	mi := &file_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitShardMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitShardMigrationRequest) ProtoMessage() {}

func (x *CommitShardMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitShardMigrationRequest.ProtoReflect.Descriptor instead.
func (*CommitShardMigrationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{30}
}

func (x *CommitShardMigrationRequest) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *CommitShardMigrationRequest) GetNewPrimaryNodeId() string {
	if x != nil {
		return x.NewPrimaryNodeId
	}
	return ""
}

func (x *CommitShardMigrationRequest) GetNewReplicaNodeIds() []string {
	if x != nil {
		return x.NewReplicaNodeIds
	}
	return nil
}

type CommitShardMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitShardMigrationResponse) Reset() {
	*x = CommitShardMigrationResponse{}
	mi := &file_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitShardMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitShardMigrationResponse) ProtoMessage() {}

func (x *CommitShardMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitShardMigrationResponse.ProtoReflect.Descriptor instead.
func (*CommitShardMigrationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{31}
}

func (x *CommitShardMigrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitShardMigrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetClusterStatusRequest requests the overall cluster status.
type GetClusterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStatusRequest) Reset() {
	*x = GetClusterStatusRequest{}
	mi := &file_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStatusRequest) ProtoMessage() {}

func (x *GetClusterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStatusRequest.ProtoReflect.Descriptor instead.
func (*GetClusterStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{32}
}

type GetClusterStatusResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	ActiveNodes      []*StorageNode            `protobuf:"bytes,1,rep,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	ShardAssignments []*ShardSlotAssignment    `protobuf:"bytes,2,rep,name=shard_assignments,json=shardAssignments,proto3" json:"shard_assignments,omitempty"`
	OnboardingStates []*ReplicaOnboardingState `protobuf:"bytes,3,rep,name=onboarding_states,json=onboardingStates,proto3" json:"onboarding_states,omitempty"`
	MigrationStates  []*ShardMigrationState    `protobuf:"bytes,4,rep,name=migration_states,json=migrationStates,proto3" json:"migration_states,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetClusterStatusResponse) Reset() {
	*x = GetClusterStatusResponse{}
	mi := &file_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStatusResponse) ProtoMessage() {}

func (x *GetClusterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStatusResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{33}
}

func (x *GetClusterStatusResponse) GetActiveNodes() []*StorageNode {
	if x != nil {
		return x.ActiveNodes
	}
	return nil
}

func (x *GetClusterStatusResponse) GetShardAssignments() []*ShardSlotAssignment {
	if x != nil {
		return x.ShardAssignments
	}
	return nil
}

func (x *GetClusterStatusResponse) GetOnboardingStates() []*ReplicaOnboardingState {
	if x != nil {
		return x.OnboardingStates
	}
	return nil
}

func (x *GetClusterStatusResponse) GetMigrationStates() []*ShardMigrationState {
	if x != nil {
		return x.MigrationStates
	}
	return nil
}

// ReplicaOnboardingState details an ongoing replica onboarding process.
type ReplicaOnboardingState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnboardingId  string                 `protobuf:"bytes,1,opt,name=onboarding_id,json=onboardingId,proto3" json:"onboarding_id,omitempty"`
	SlotId        uint32                 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	ReplicaNodeId string                 `protobuf:"bytes,3,opt,name=replica_node_id,json=replicaNodeId,proto3" json:"replica_node_id,omitempty"`
	PrimaryNodeId string                 `protobuf:"bytes,4,opt,name=primary_node_id,json=primaryNodeId,proto3" json:"primary_node_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // e.g., "snapshotting", "log_catching_up", "completed", "failed"
	CurrentLsn    uint64                 `protobuf:"varint,6,opt,name=current_lsn,json=currentLsn,proto3" json:"current_lsn,omitempty"`
	TargetLsn     uint64                 `protobuf:"varint,7,opt,name=target_lsn,json=targetLsn,proto3" json:"target_lsn,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaOnboardingState) Reset() {
	*x = ReplicaOnboardingState{}
	mi := &file_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaOnboardingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaOnboardingState) ProtoMessage() {}

func (x *ReplicaOnboardingState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaOnboardingState.ProtoReflect.Descriptor instead.
func (*ReplicaOnboardingState) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{34}
}

func (x *ReplicaOnboardingState) GetOnboardingId() string {
	if x != nil {
		return x.OnboardingId
	}
	return ""
}

func (x *ReplicaOnboardingState) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *ReplicaOnboardingState) GetReplicaNodeId() string {
	if x != nil {
		return x.ReplicaNodeId
	}
	return ""
}

func (x *ReplicaOnboardingState) GetPrimaryNodeId() string {
	if x != nil {
		return x.PrimaryNodeId
	}
	return ""
}

func (x *ReplicaOnboardingState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReplicaOnboardingState) GetCurrentLsn() uint64 {
	if x != nil {
		return x.CurrentLsn
	}
	return 0
}

func (x *ReplicaOnboardingState) GetTargetLsn() uint64 {
	if x != nil {
		return x.TargetLsn
	}
	return 0
}

func (x *ReplicaOnboardingState) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ShardMigrationState details an ongoing shard migration process.
type ShardMigrationState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   string                 `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	SlotId        uint32                 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	SourceNodeId  string                 `protobuf:"bytes,3,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,4,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // e.g., "snapshotting", "log_catching_up", "completed", "failed"
	CurrentLsn    uint64                 `protobuf:"varint,6,opt,name=current_lsn,json=currentLsn,proto3" json:"current_lsn,omitempty"`
	TargetLsn     uint64                 `protobuf:"varint,7,opt,name=target_lsn,json=targetLsn,proto3" json:"target_lsn,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardMigrationState) Reset() {
	*x = ShardMigrationState{}
	mi := &file_api_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardMigrationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardMigrationState) ProtoMessage() {}

func (x *ShardMigrationState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardMigrationState.ProtoReflect.Descriptor instead.
func (*ShardMigrationState) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{35}
}

func (x *ShardMigrationState) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *ShardMigrationState) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *ShardMigrationState) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *ShardMigrationState) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *ShardMigrationState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShardMigrationState) GetCurrentLsn() uint64 {
	if x != nil {
		return x.CurrentLsn
	}
	return 0
}

func (x *ShardMigrationState) GetTargetLsn() uint64 {
	if x != nil {
		return x.TargetLsn
	}
	return 0
}

func (x *ShardMigrationState) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetShardMapRequest requests the current shard map.
type GetShardMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardMapRequest) Reset() {
	*x = GetShardMapRequest{}
	mi := &file_api_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardMapRequest) ProtoMessage() {}

func (x *GetShardMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardMapRequest.ProtoReflect.Descriptor instead.
func (*GetShardMapRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{36}
}

type GetShardMapResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ShardAssignments []*ShardSlotAssignment `protobuf:"bytes,1,rep,name=shard_assignments,json=shardAssignments,proto3" json:"shard_assignments,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetShardMapResponse) Reset() {
	*x = GetShardMapResponse{}
	mi := &file_api_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardMapResponse) ProtoMessage() {}

func (x *GetShardMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardMapResponse.ProtoReflect.Descriptor instead.
func (*GetShardMapResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{37}
}

func (x *GetShardMapResponse) GetShardAssignments() []*ShardSlotAssignment {
	if x != nil {
		return x.ShardAssignments
	}
	return nil
}

type StreamSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotId        uint32                 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	IndexType     string                 `protobuf:"bytes,2,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"`    // e.g., "btree", "inverted", "spatial"
	SnapshotId    string                 `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"` // ID of the prepared snapshot on the source node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSnapshotRequest) Reset() {
	*x = StreamSnapshotRequest{}
	mi := &file_api_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSnapshotRequest) ProtoMessage() {}

func (x *StreamSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSnapshotRequest.ProtoReflect.Descriptor instead.
func (*StreamSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{38}
}

func (x *StreamSnapshotRequest) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *StreamSnapshotRequest) GetIndexType() string {
	if x != nil {
		return x.IndexType
	}
	return ""
}

func (x *StreamSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type StreamSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSnapshotResponse) Reset() {
	*x = StreamSnapshotResponse{}
	mi := &file_api_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSnapshotResponse) ProtoMessage() {}

func (x *StreamSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSnapshotResponse.ProtoReflect.Descriptor instead.
func (*StreamSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{39}
}

func (x *StreamSnapshotResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x05proto\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"A\n" +
	"\vPutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x0fGetRangeRequest\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\tR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\tR\x06endKey\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"6\n" +
	"\fKeyValuePair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"A\n" +
	"\x10GetRangeResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.proto.KeyValuePairR\aentries\"^\n" +
	"\x11TextSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"index_name\x18\x02 \x01(\tR\tindexName\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\":\n" +
	"\x10TextSearchResult\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"G\n" +
	"\x12TextSearchResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.proto.TextSearchResultR\aresults\"?\n" +
	"\x0eBulkPutRequest\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.proto.KeyValuePairR\aentries\"E\n" +
	"\x0fBulkPutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\x11BulkDeleteRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"H\n" +
	"\x12BulkDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"X\n" +
	"\vStorageNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"J\n" +
	"\x15AddStorageNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"L\n" +
	"\x16AddStorageNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x18RemoveStorageNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"O\n" +
	"\x19RemoveStorageNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x80\x01\n" +
	"\x13ShardSlotAssignment\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12&\n" +
	"\x0fprimary_node_id\x18\x02 \x01(\tR\rprimaryNodeId\x12(\n" +
	"\x10replica_node_ids\x18\x03 \x03(\tR\x0ereplicaNodeIds\"\x83\x01\n" +
	"\x16AssignShardSlotRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12&\n" +
	"\x0fprimary_node_id\x18\x02 \x01(\tR\rprimaryNodeId\x12(\n" +
	"\x10replica_node_ids\x18\x03 \x03(\tR\x0ereplicaNodeIds\"M\n" +
	"\x17AssignShardSlotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xdd\x01\n" +
	" InitiateReplicaOnboardingRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12&\n" +
	"\x0freplica_node_id\x18\x02 \x01(\tR\rreplicaNodeId\x12&\n" +
	"\x0fprimary_node_id\x18\x03 \x01(\tR\rprimaryNodeId\x12'\n" +
	"\x0freplica_address\x18\x04 \x01(\tR\x0ereplicaAddress\x12'\n" +
	"\x0fprimary_address\x18\x05 \x01(\tR\x0eprimaryAddress\"|\n" +
	"!InitiateReplicaOnboardingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\ronboarding_id\x18\x03 \x01(\tR\fonboardingId\"\xc7\x01\n" +
	"#UpdateReplicaOnboardingStateRequest\x12#\n" +
	"\ronboarding_id\x18\x01 \x01(\tR\fonboardingId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vcurrent_lsn\x18\x03 \x01(\x04R\n" +
	"currentLsn\x12\x1d\n" +
	"\n" +
	"target_lsn\x18\x04 \x01(\x04R\ttargetLsn\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"Z\n" +
	"$UpdateReplicaOnboardingStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd2\x01\n" +
	"\x1dInitiateShardMigrationRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12$\n" +
	"\x0esource_node_id\x18\x02 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\x12%\n" +
	"\x0esource_address\x18\x04 \x01(\tR\rsourceAddress\x12%\n" +
	"\x0etarget_address\x18\x05 \x01(\tR\rtargetAddress\"w\n" +
	"\x1eInitiateShardMigrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fmigration_id\x18\x03 \x01(\tR\vmigrationId\"\x96\x01\n" +
	"\x1bCommitShardMigrationRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12-\n" +
	"\x13new_primary_node_id\x18\x02 \x01(\tR\x10newPrimaryNodeId\x12/\n" +
	"\x14new_replica_node_ids\x18\x03 \x03(\tR\x11newReplicaNodeIds\"R\n" +
	"\x1cCommitShardMigrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x19\n" +
	"\x17GetClusterStatusRequest\"\xad\x02\n" +
	"\x18GetClusterStatusResponse\x125\n" +
	"\factive_nodes\x18\x01 \x03(\v2\x12.proto.StorageNodeR\vactiveNodes\x12G\n" +
	"\x11shard_assignments\x18\x02 \x03(\v2\x1a.proto.ShardSlotAssignmentR\x10shardAssignments\x12J\n" +
	"\x11onboarding_states\x18\x03 \x03(\v2\x1d.proto.ReplicaOnboardingStateR\x10onboardingStates\x12E\n" +
	"\x10migration_states\x18\x04 \x03(\v2\x1a.proto.ShardMigrationStateR\x0fmigrationStates\"\xa3\x02\n" +
	"\x16ReplicaOnboardingState\x12#\n" +
	"\ronboarding_id\x18\x01 \x01(\tR\fonboardingId\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\rR\x06slotId\x12&\n" +
	"\x0freplica_node_id\x18\x03 \x01(\tR\rreplicaNodeId\x12&\n" +
	"\x0fprimary_node_id\x18\x04 \x01(\tR\rprimaryNodeId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vcurrent_lsn\x18\x06 \x01(\x04R\n" +
	"currentLsn\x12\x1d\n" +
	"\n" +
	"target_lsn\x18\a \x01(\x04R\ttargetLsn\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"\x9a\x02\n" +
	"\x13ShardMigrationState\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\x12\x17\n" +
	"\aslot_id\x18\x02 \x01(\rR\x06slotId\x12$\n" +
	"\x0esource_node_id\x18\x03 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x04 \x01(\tR\ftargetNodeId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vcurrent_lsn\x18\x06 \x01(\x04R\n" +
	"currentLsn\x12\x1d\n" +
	"\n" +
	"target_lsn\x18\a \x01(\x04R\ttargetLsn\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"\x14\n" +
	"\x12GetShardMapRequest\"^\n" +
	"\x13GetShardMapResponse\x12G\n" +
	"\x11shard_assignments\x18\x01 \x03(\v2\x1a.proto.ShardSlotAssignmentR\x10shardAssignments\"p\n" +
	"\x15StreamSnapshotRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\rR\x06slotId\x12\x1d\n" +
	"\n" +
	"index_type\x18\x02 \x01(\tR\tindexType\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\tR\n" +
	"snapshotId\".\n" +
	"\x16StreamSnapshotResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2\xe5\t\n" +
	"\x0eGatewayService\x12,\n" +
	"\x03Put\x12\x11.proto.PutRequest\x1a\x12.proto.PutResponse\x12,\n" +
	"\x03Get\x12\x11.proto.GetRequest\x1a\x12.proto.GetResponse\x125\n" +
	"\x06Delete\x12\x14.proto.DeleteRequest\x1a\x15.proto.DeleteResponse\x12;\n" +
	"\bGetRange\x12\x16.proto.GetRangeRequest\x1a\x17.proto.GetRangeResponse\x12A\n" +
	"\n" +
	"TextSearch\x12\x18.proto.TextSearchRequest\x1a\x19.proto.TextSearchResponse\x128\n" +
	"\aBulkPut\x12\x15.proto.BulkPutRequest\x1a\x16.proto.BulkPutResponse\x12A\n" +
	"\n" +
	"BulkDelete\x12\x18.proto.BulkDeleteRequest\x1a\x19.proto.BulkDeleteResponse\x12M\n" +
	"\x0eAddStorageNode\x12\x1c.proto.AddStorageNodeRequest\x1a\x1d.proto.AddStorageNodeResponse\x12V\n" +
	"\x11RemoveStorageNode\x12\x1f.proto.RemoveStorageNodeRequest\x1a .proto.RemoveStorageNodeResponse\x12P\n" +
	"\x0fAssignShardSlot\x12\x1d.proto.AssignShardSlotRequest\x1a\x1e.proto.AssignShardSlotResponse\x12n\n" +
	"\x19InitiateReplicaOnboarding\x12'.proto.InitiateReplicaOnboardingRequest\x1a(.proto.InitiateReplicaOnboardingResponse\x12w\n" +
	"\x1cUpdateReplicaOnboardingState\x12*.proto.UpdateReplicaOnboardingStateRequest\x1a+.proto.UpdateReplicaOnboardingStateResponse\x12e\n" +
	"\x16InitiateShardMigration\x12$.proto.InitiateShardMigrationRequest\x1a%.proto.InitiateShardMigrationResponse\x12_\n" +
	"\x14CommitShardMigration\x12\".proto.CommitShardMigrationRequest\x1a#.proto.CommitShardMigrationResponse\x12S\n" +
	"\x10GetClusterStatus\x12\x1e.proto.GetClusterStatusRequest\x1a\x1f.proto.GetClusterStatusResponse\x12D\n" +
	"\vGetShardMap\x12\x19.proto.GetShardMapRequest\x1a\x1a.proto.GetShardMapResponse2b\n" +
	"\x0fSnapshotService\x12O\n" +
	"\x0eStreamSnapshot\x12\x1c.proto.StreamSnapshotRequest\x1a\x1d.proto.StreamSnapshotResponse0\x012\xf7\x01\n" +
	"\x13IndexedWriteService\x12,\n" +
	"\x03Put\x12\x11.proto.PutRequest\x1a\x12.proto.PutResponse\x125\n" +
	"\x06Delete\x12\x14.proto.DeleteRequest\x1a\x15.proto.DeleteResponse\x128\n" +
	"\aBulkPut\x12\x15.proto.BulkPutRequest\x1a\x16.proto.BulkPutResponse\x12A\n" +
	"\n" +
	"BulkDelete\x12\x18.proto.BulkDeleteRequest\x1a\x19.proto.BulkDeleteResponse2\xc2\x01\n" +
	"\x12IndexedReadService\x12,\n" +
	"\x03Get\x12\x11.proto.GetRequest\x1a\x12.proto.GetResponse\x12;\n" +
	"\bGetRange\x12\x16.proto.GetRangeRequest\x1a\x17.proto.GetRangeResponse\x12A\n" +
	"\n" +
	"TextSearch\x12\x18.proto.TextSearchRequest\x1a\x19.proto.TextSearchResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_api_proto_goTypes = []any{
	(*PutRequest)(nil),                           // 0: proto.PutRequest
	(*PutResponse)(nil),                          // 1: proto.PutResponse
	(*GetRequest)(nil),                           // 2: proto.GetRequest
	(*GetResponse)(nil),                          // 3: proto.GetResponse
	(*DeleteRequest)(nil),                        // 4: proto.DeleteRequest
	(*DeleteResponse)(nil),                       // 5: proto.DeleteResponse
	(*GetRangeRequest)(nil),                      // 6: proto.GetRangeRequest
	(*KeyValuePair)(nil),                         // 7: proto.KeyValuePair
	(*GetRangeResponse)(nil),                     // 8: proto.GetRangeResponse
	(*TextSearchRequest)(nil),                    // 9: proto.TextSearchRequest
	(*TextSearchResult)(nil),                     // 10: proto.TextSearchResult
	(*TextSearchResponse)(nil),                   // 11: proto.TextSearchResponse
	(*BulkPutRequest)(nil),                       // 12: proto.BulkPutRequest
	(*BulkPutResponse)(nil),                      // 13: proto.BulkPutResponse
	(*BulkDeleteRequest)(nil),                    // 14: proto.BulkDeleteRequest
	(*BulkDeleteResponse)(nil),                   // 15: proto.BulkDeleteResponse
	(*StorageNode)(nil),                          // 16: proto.StorageNode
	(*AddStorageNodeRequest)(nil),                // 17: proto.AddStorageNodeRequest
	(*AddStorageNodeResponse)(nil),               // 18: proto.AddStorageNodeResponse
	(*RemoveStorageNodeRequest)(nil),             // 19: proto.RemoveStorageNodeRequest
	(*RemoveStorageNodeResponse)(nil),            // 20: proto.RemoveStorageNodeResponse
	(*ShardSlotAssignment)(nil),                  // 21: proto.ShardSlotAssignment
	(*AssignShardSlotRequest)(nil),               // 22: proto.AssignShardSlotRequest
	(*AssignShardSlotResponse)(nil),              // 23: proto.AssignShardSlotResponse
	(*InitiateReplicaOnboardingRequest)(nil),     // 24: proto.InitiateReplicaOnboardingRequest
	(*InitiateReplicaOnboardingResponse)(nil),    // 25: proto.InitiateReplicaOnboardingResponse
	(*UpdateReplicaOnboardingStateRequest)(nil),  // 26: proto.UpdateReplicaOnboardingStateRequest
	(*UpdateReplicaOnboardingStateResponse)(nil), // 27: proto.UpdateReplicaOnboardingStateResponse
	(*InitiateShardMigrationRequest)(nil),        // 28: proto.InitiateShardMigrationRequest
	(*InitiateShardMigrationResponse)(nil),       // 29: proto.InitiateShardMigrationResponse
	(*CommitShardMigrationRequest)(nil),          // 30: proto.CommitShardMigrationRequest
	(*CommitShardMigrationResponse)(nil),         // 31: proto.CommitShardMigrationResponse
	(*GetClusterStatusRequest)(nil),              // 32: proto.GetClusterStatusRequest
	(*GetClusterStatusResponse)(nil),             // 33: proto.GetClusterStatusResponse
	(*ReplicaOnboardingState)(nil),               // 34: proto.ReplicaOnboardingState
	(*ShardMigrationState)(nil),                  // 35: proto.ShardMigrationState
	(*GetShardMapRequest)(nil),                   // 36: proto.GetShardMapRequest
	(*GetShardMapResponse)(nil),                  // 37: proto.GetShardMapResponse
	(*StreamSnapshotRequest)(nil),                // 38: proto.StreamSnapshotRequest
	(*StreamSnapshotResponse)(nil),               // 39: proto.StreamSnapshotResponse
}
var file_api_proto_depIdxs = []int32{
	7,  // 0: proto.GetRangeResponse.entries:type_name -> proto.KeyValuePair
	10, // 1: proto.TextSearchResponse.results:type_name -> proto.TextSearchResult
	7,  // 2: proto.BulkPutRequest.entries:type_name -> proto.KeyValuePair
	16, // 3: proto.GetClusterStatusResponse.active_nodes:type_name -> proto.StorageNode
	21, // 4: proto.GetClusterStatusResponse.shard_assignments:type_name -> proto.ShardSlotAssignment
	34, // 5: proto.GetClusterStatusResponse.onboarding_states:type_name -> proto.ReplicaOnboardingState
	35, // 6: proto.GetClusterStatusResponse.migration_states:type_name -> proto.ShardMigrationState
	21, // 7: proto.GetShardMapResponse.shard_assignments:type_name -> proto.ShardSlotAssignment
	0,  // 8: proto.GatewayService.Put:input_type -> proto.PutRequest
	2,  // 9: proto.GatewayService.Get:input_type -> proto.GetRequest
	4,  // 10: proto.GatewayService.Delete:input_type -> proto.DeleteRequest
	6,  // 11: proto.GatewayService.GetRange:input_type -> proto.GetRangeRequest
	9,  // 12: proto.GatewayService.TextSearch:input_type -> proto.TextSearchRequest
	12, // 13: proto.GatewayService.BulkPut:input_type -> proto.BulkPutRequest
	14, // 14: proto.GatewayService.BulkDelete:input_type -> proto.BulkDeleteRequest
	17, // 15: proto.GatewayService.AddStorageNode:input_type -> proto.AddStorageNodeRequest
	19, // 16: proto.GatewayService.RemoveStorageNode:input_type -> proto.RemoveStorageNodeRequest
	22, // 17: proto.GatewayService.AssignShardSlot:input_type -> proto.AssignShardSlotRequest
	24, // 18: proto.GatewayService.InitiateReplicaOnboarding:input_type -> proto.InitiateReplicaOnboardingRequest
	26, // 19: proto.GatewayService.UpdateReplicaOnboardingState:input_type -> proto.UpdateReplicaOnboardingStateRequest
	28, // 20: proto.GatewayService.InitiateShardMigration:input_type -> proto.InitiateShardMigrationRequest
	30, // 21: proto.GatewayService.CommitShardMigration:input_type -> proto.CommitShardMigrationRequest
	32, // 22: proto.GatewayService.GetClusterStatus:input_type -> proto.GetClusterStatusRequest
	36, // 23: proto.GatewayService.GetShardMap:input_type -> proto.GetShardMapRequest
	38, // 24: proto.SnapshotService.StreamSnapshot:input_type -> proto.StreamSnapshotRequest
	0,  // 25: proto.IndexedWriteService.Put:input_type -> proto.PutRequest
	4,  // 26: proto.IndexedWriteService.Delete:input_type -> proto.DeleteRequest
	12, // 27: proto.IndexedWriteService.BulkPut:input_type -> proto.BulkPutRequest
	14, // 28: proto.IndexedWriteService.BulkDelete:input_type -> proto.BulkDeleteRequest
	2,  // 29: proto.IndexedReadService.Get:input_type -> proto.GetRequest
	6,  // 30: proto.IndexedReadService.GetRange:input_type -> proto.GetRangeRequest
	9,  // 31: proto.IndexedReadService.TextSearch:input_type -> proto.TextSearchRequest
	1,  // 32: proto.GatewayService.Put:output_type -> proto.PutResponse
	3,  // 33: proto.GatewayService.Get:output_type -> proto.GetResponse
	5,  // 34: proto.GatewayService.Delete:output_type -> proto.DeleteResponse
	8,  // 35: proto.GatewayService.GetRange:output_type -> proto.GetRangeResponse
	11, // 36: proto.GatewayService.TextSearch:output_type -> proto.TextSearchResponse
	13, // 37: proto.GatewayService.BulkPut:output_type -> proto.BulkPutResponse
	15, // 38: proto.GatewayService.BulkDelete:output_type -> proto.BulkDeleteResponse
	18, // 39: proto.GatewayService.AddStorageNode:output_type -> proto.AddStorageNodeResponse
	20, // 40: proto.GatewayService.RemoveStorageNode:output_type -> proto.RemoveStorageNodeResponse
	23, // 41: proto.GatewayService.AssignShardSlot:output_type -> proto.AssignShardSlotResponse
	25, // 42: proto.GatewayService.InitiateReplicaOnboarding:output_type -> proto.InitiateReplicaOnboardingResponse
	27, // 43: proto.GatewayService.UpdateReplicaOnboardingState:output_type -> proto.UpdateReplicaOnboardingStateResponse
	29, // 44: proto.GatewayService.InitiateShardMigration:output_type -> proto.InitiateShardMigrationResponse
	31, // 45: proto.GatewayService.CommitShardMigration:output_type -> proto.CommitShardMigrationResponse
	33, // 46: proto.GatewayService.GetClusterStatus:output_type -> proto.GetClusterStatusResponse
	37, // 47: proto.GatewayService.GetShardMap:output_type -> proto.GetShardMapResponse
	39, // 48: proto.SnapshotService.StreamSnapshot:output_type -> proto.StreamSnapshotResponse
	1,  // 49: proto.IndexedWriteService.Put:output_type -> proto.PutResponse
	5,  // 50: proto.IndexedWriteService.Delete:output_type -> proto.DeleteResponse
	13, // 51: proto.IndexedWriteService.BulkPut:output_type -> proto.BulkPutResponse
	15, // 52: proto.IndexedWriteService.BulkDelete:output_type -> proto.BulkDeleteResponse
	3,  // 53: proto.IndexedReadService.Get:output_type -> proto.GetResponse
	8,  // 54: proto.IndexedReadService.GetRange:output_type -> proto.GetRangeResponse
	11, // 55: proto.IndexedReadService.TextSearch:output_type -> proto.TextSearchResponse
	32, // [32:56] is the sub-list for method output_type
	8,  // [8:32] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
