// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpatialQueryType int32

const (
	SpatialQueryType_INTERSECTS SpatialQueryType = 0
	SpatialQueryType_CONTAINS   SpatialQueryType = 1 // Query shape contains document shapes
	SpatialQueryType_WITHIN     SpatialQueryType = 2 // Document shapes are within query shape
)

// Enum value maps for SpatialQueryType.
var (
	SpatialQueryType_name = map[int32]string{
		0: "INTERSECTS",
		1: "CONTAINS",
		2: "WITHIN",
	}
	SpatialQueryType_value = map[string]int32{
		"INTERSECTS": 0,
		"CONTAINS":   1,
		"WITHIN":     2,
	}
)

func (x SpatialQueryType) Enum() *SpatialQueryType {
	p := new(SpatialQueryType)
	*p = x
	return p
}

func (x SpatialQueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpatialQueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (SpatialQueryType) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x SpatialQueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpatialQueryType.Descriptor instead.
func (SpatialQueryType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type OperationType int32

const (
	OperationType_UPSERT OperationType = 0 // Insert or Update
	OperationType_DELETE OperationType = 1
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "UPSERT",
		1: "DELETE",
	}
	OperationType_value = map[string]int32{
		"UPSERT": 0,
		"DELETE": 1,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[1].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[1]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

type SortDirection int32

const (
	SortDirection_ASC  SortDirection = 0
	SortDirection_DESC SortDirection = 1
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "ASC",
		1: "DESC",
	}
	SortDirection_value = map[string]int32{
		"ASC":  0,
		"DESC": 1,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[2].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[2]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

type Accumulator_AccumulatorType int32

const (
	Accumulator_SUM   Accumulator_AccumulatorType = 0
	Accumulator_AVG   Accumulator_AccumulatorType = 1
	Accumulator_MIN   Accumulator_AccumulatorType = 2
	Accumulator_MAX   Accumulator_AccumulatorType = 3
	Accumulator_COUNT Accumulator_AccumulatorType = 4 // Counts documents in group
	Accumulator_FIRST Accumulator_AccumulatorType = 5
	Accumulator_LAST  Accumulator_AccumulatorType = 6
	Accumulator_PUSH  Accumulator_AccumulatorType = 7 // Creates an array of values (more complex)
)

// Enum value maps for Accumulator_AccumulatorType.
var (
	Accumulator_AccumulatorType_name = map[int32]string{
		0: "SUM",
		1: "AVG",
		2: "MIN",
		3: "MAX",
		4: "COUNT",
		5: "FIRST",
		6: "LAST",
		7: "PUSH",
	}
	Accumulator_AccumulatorType_value = map[string]int32{
		"SUM":   0,
		"AVG":   1,
		"MIN":   2,
		"MAX":   3,
		"COUNT": 4,
		"FIRST": 5,
		"LAST":  6,
		"PUSH":  7,
	}
)

func (x Accumulator_AccumulatorType) Enum() *Accumulator_AccumulatorType {
	p := new(Accumulator_AccumulatorType)
	*p = x
	return p
}

func (x Accumulator_AccumulatorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Accumulator_AccumulatorType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[3].Descriptor()
}

func (Accumulator_AccumulatorType) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[3]
}

func (x Accumulator_AccumulatorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Accumulator_AccumulatorType.Descriptor instead.
func (Accumulator_AccumulatorType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22, 0}
}

// Common Messages
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // Unique ID of the document
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                                                                   // Document content as a JSON-like structure
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional metadata (e.g., content_type, source)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Document) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GeoPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoPoint) Reset() {
	*x = GeoPoint{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPoint) ProtoMessage() {}

func (x *GeoPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPoint.ProtoReflect.Descriptor instead.
func (*GeoPoint) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *GeoPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GeoShape struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Could be a polygon, circle, etc. For simplicity, let's assume a bounding box for now.
	TopLeft       *GeoPoint `protobuf:"bytes,1,opt,name=top_left,json=topLeft,proto3" json:"top_left,omitempty"`
	BottomRight   *GeoPoint `protobuf:"bytes,2,opt,name=bottom_right,json=bottomRight,proto3" json:"bottom_right,omitempty"` // TODO: Add more shape types (e.g., using a oneof for different geometric types)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoShape) Reset() {
	*x = GeoShape{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoShape) ProtoMessage() {}

func (x *GeoShape) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoShape.ProtoReflect.Descriptor instead.
func (*GeoShape) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *GeoShape) GetTopLeft() *GeoPoint {
	if x != nil {
		return x.TopLeft
	}
	return nil
}

func (x *GeoShape) GetBottomRight() *GeoPoint {
	if x != nil {
		return x.BottomRight
	}
	return nil
}

type WriteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Optional message, e.g., error details
	Lsn           string                 `protobuf:"bytes,4,opt,name=lsn,proto3" json:"lsn,omitempty"`         // Log Sequence Number for the write operation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResult) Reset() {
	*x = WriteResult{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResult) ProtoMessage() {}

func (x *WriteResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResult.ProtoReflect.Descriptor instead.
func (*WriteResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *WriteResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WriteResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WriteResult) GetLsn() string {
	if x != nil {
		return x.Lsn
	}
	return ""
}

type IndexedWriteRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Document *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// Optional: Specify which indexes to update explicitly. If empty, update all applicable.
	IndexesToUpdate []string `protobuf:"bytes,2,rep,name=indexes_to_update,json=indexesToUpdate,proto3" json:"indexes_to_update,omitempty"` // e.g., ["inverted", "spatial"]
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IndexedWriteRequest) Reset() {
	*x = IndexedWriteRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexedWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexedWriteRequest) ProtoMessage() {}

func (x *IndexedWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexedWriteRequest.ProtoReflect.Descriptor instead.
func (*IndexedWriteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *IndexedWriteRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *IndexedWriteRequest) GetIndexesToUpdate() []string {
	if x != nil {
		return x.IndexesToUpdate
	}
	return nil
}

type UpdateInvertedIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TextFields    map[string]string      `protobuf:"bytes,2,rep,name=text_fields,json=textFields,proto3" json:"text_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Field name to text content for indexing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInvertedIndexRequest) Reset() {
	*x = UpdateInvertedIndexRequest{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvertedIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvertedIndexRequest) ProtoMessage() {}

func (x *UpdateInvertedIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvertedIndexRequest.ProtoReflect.Descriptor instead.
func (*UpdateInvertedIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateInvertedIndexRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateInvertedIndexRequest) GetTextFields() map[string]string {
	if x != nil {
		return x.TextFields
	}
	return nil
}

type UpdateSpatialIndexRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	DocumentId    string                     `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Shape         *GeoShape                  `protobuf:"bytes,2,opt,name=shape,proto3" json:"shape,omitempty"`
	Attributes    map[string]*structpb.Value `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional attributes for the spatial entry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpatialIndexRequest) Reset() {
	*x = UpdateSpatialIndexRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpatialIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpatialIndexRequest) ProtoMessage() {}

func (x *UpdateSpatialIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpatialIndexRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpatialIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSpatialIndexRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateSpatialIndexRequest) GetShape() *GeoShape {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *UpdateSpatialIndexRequest) GetAttributes() map[string]*structpb.Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *GetDocumentResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SearchInvertedIndexRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // Search query (e.g., "term1 AND term2 NOT term3")
	// TODO: Add pagination, sorting, filtering options
	Limit          int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	FieldsToSearch []string `protobuf:"bytes,4,rep,name=fields_to_search,json=fieldsToSearch,proto3" json:"fields_to_search,omitempty"` // Optional: specify fields to search in
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchInvertedIndexRequest) Reset() {
	*x = SearchInvertedIndexRequest{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchInvertedIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchInvertedIndexRequest) ProtoMessage() {}

func (x *SearchInvertedIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchInvertedIndexRequest.ProtoReflect.Descriptor instead.
func (*SearchInvertedIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *SearchInvertedIndexRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchInvertedIndexRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchInvertedIndexRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchInvertedIndexRequest) GetFieldsToSearch() []string {
	if x != nil {
		return x.FieldsToSearch
	}
	return nil
}

type SearchSpatialIndexRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	QueryShape *GeoShape              `protobuf:"bytes,1,opt,name=query_shape,json=queryShape,proto3" json:"query_shape,omitempty"`                           // The shape to query against (e.g., find documents within this shape)
	QueryType  SpatialQueryType       `protobuf:"varint,2,opt,name=query_type,json=queryType,proto3,enum=proto.SpatialQueryType" json:"query_type,omitempty"` // e.g., INTERSECTS, CONTAINS, WITHIN
	// TODO: Add pagination, filtering by attributes
	Limit         int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSpatialIndexRequest) Reset() {
	*x = SearchSpatialIndexRequest{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSpatialIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSpatialIndexRequest) ProtoMessage() {}

func (x *SearchSpatialIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSpatialIndexRequest.ProtoReflect.Descriptor instead.
func (*SearchSpatialIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *SearchSpatialIndexRequest) GetQueryShape() *GeoShape {
	if x != nil {
		return x.QueryShape
	}
	return nil
}

func (x *SearchSpatialIndexRequest) GetQueryType() SpatialQueryType {
	if x != nil {
		return x.QueryType
	}
	return SpatialQueryType_INTERSECTS
}

func (x *SearchSpatialIndexRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchSpatialIndexRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	TotalHits     int64                  `protobuf:"varint,2,opt,name=total_hits,json=totalHits,proto3" json:"total_hits,omitempty"` // Total number of matching documents (can be an estimate)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *SearchResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *SearchResponse) GetTotalHits() int64 {
	if x != nil {
		return x.TotalHits
	}
	return 0
}

type RangeScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      string                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"` // Inclusive start key
	EndKey        string                 `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`       // Exclusive end key
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                      // Max number of documents to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeScanRequest) Reset() {
	*x = RangeScanRequest{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeScanRequest) ProtoMessage() {}

func (x *RangeScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeScanRequest.ProtoReflect.Descriptor instead.
func (*RangeScanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *RangeScanRequest) GetStartKey() string {
	if x != nil {
		return x.StartKey
	}
	return ""
}

func (x *RangeScanRequest) GetEndKey() string {
	if x != nil {
		return x.EndKey
	}
	return ""
}

func (x *RangeScanRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BulkOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationType OperationType          `protobuf:"varint,1,opt,name=operation_type,json=operationType,proto3,enum=proto.OperationType" json:"operation_type,omitempty"`
	Document      *Document              `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"` // Used for UPSERT. For DELETE, document.id is used.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkOperation) Reset() {
	*x = BulkOperation{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkOperation) ProtoMessage() {}

func (x *BulkOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkOperation.ProtoReflect.Descriptor instead.
func (*BulkOperation) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *BulkOperation) GetOperationType() OperationType {
	if x != nil {
		return x.OperationType
	}
	return OperationType_UPSERT
}

func (x *BulkOperation) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type BulkWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*BulkOperation       `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"` // Optional: could add transactionality hints, error handling preferences (e.g., fail fast vs continue on error)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkWriteRequest) Reset() {
	*x = BulkWriteRequest{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkWriteRequest) ProtoMessage() {}

func (x *BulkWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkWriteRequest.ProtoReflect.Descriptor instead.
func (*BulkWriteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *BulkWriteRequest) GetOperations() []*BulkOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type BulkWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*WriteResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // Result for each operation in the batch
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount  int32                  `protobuf:"varint,3,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkWriteResponse) Reset() {
	*x = BulkWriteResponse{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkWriteResponse) ProtoMessage() {}

func (x *BulkWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkWriteResponse.ProtoReflect.Descriptor instead.
func (*BulkWriteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *BulkWriteResponse) GetResults() []*WriteResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BulkWriteResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BulkWriteResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

type BulkWriteSummaryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalOperations    int32                  `protobuf:"varint,1,opt,name=total_operations,json=totalOperations,proto3" json:"total_operations,omitempty"`
	SuccessCount       int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount       int32                  `protobuf:"varint,3,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	FailedOperationIds []string               `protobuf:"bytes,4,rep,name=failed_operation_ids,json=failedOperationIds,proto3" json:"failed_operation_ids,omitempty"` // IDs of documents that failed
	FirstErrorMessage  string                 `protobuf:"bytes,5,opt,name=first_error_message,json=firstErrorMessage,proto3" json:"first_error_message,omitempty"`    // Message of the first error encountered
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BulkWriteSummaryResponse) Reset() {
	*x = BulkWriteSummaryResponse{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkWriteSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkWriteSummaryResponse) ProtoMessage() {}

func (x *BulkWriteSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkWriteSummaryResponse.ProtoReflect.Descriptor instead.
func (*BulkWriteSummaryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *BulkWriteSummaryResponse) GetTotalOperations() int32 {
	if x != nil {
		return x.TotalOperations
	}
	return 0
}

func (x *BulkWriteSummaryResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BulkWriteSummaryResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *BulkWriteSummaryResponse) GetFailedOperationIds() []string {
	if x != nil {
		return x.FailedOperationIds
	}
	return nil
}

func (x *BulkWriteSummaryResponse) GetFirstErrorMessage() string {
	if x != nil {
		return x.FirstErrorMessage
	}
	return ""
}

type AggregationRequest struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	CollectionName string                      `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"` // Or table name; target of aggregation
	Stages         []*AggregationPipelineStage `protobuf:"bytes,2,rep,name=stages,proto3" json:"stages,omitempty"`                                       // Sequence of aggregation stages
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AggregationRequest) Reset() {
	*x = AggregationRequest{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationRequest) ProtoMessage() {}

func (x *AggregationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationRequest.ProtoReflect.Descriptor instead.
func (*AggregationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *AggregationRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *AggregationRequest) GetStages() []*AggregationPipelineStage {
	if x != nil {
		return x.Stages
	}
	return nil
}

type AggregationPipelineStage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to StageType:
	//
	//	*AggregationPipelineStage_Match
	//	*AggregationPipelineStage_Group
	//	*AggregationPipelineStage_Sort
	//	*AggregationPipelineStage_Project
	//	*AggregationPipelineStage_Limit
	//	*AggregationPipelineStage_Skip
	//	*AggregationPipelineStage_Count
	StageType     isAggregationPipelineStage_StageType `protobuf_oneof:"stage_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregationPipelineStage) Reset() {
	*x = AggregationPipelineStage{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationPipelineStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationPipelineStage) ProtoMessage() {}

func (x *AggregationPipelineStage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationPipelineStage.ProtoReflect.Descriptor instead.
func (*AggregationPipelineStage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *AggregationPipelineStage) GetStageType() isAggregationPipelineStage_StageType {
	if x != nil {
		return x.StageType
	}
	return nil
}

func (x *AggregationPipelineStage) GetMatch() *MatchStage {
	if x != nil {
		if x, ok := x.StageType.(*AggregationPipelineStage_Match); ok {
			return x.Match
		}
	}
	return nil
}

func (x *AggregationPipelineStage) GetGroup() *GroupStage {
	if x != nil {
		if x, ok := x.StageType.(*AggregationPipelineStage_Group); ok {
			return x.Group
		}
	}
	return nil
}

func (x *AggregationPipelineStage) GetSort() *SortStage {
	if x != nil {
		if x, ok := x.StageType.(*AggregationPipelineStage_Sort); ok {
			return x.Sort
		}
	}
	return nil
}

func (x *AggregationPipelineStage) GetProject() *ProjectStage {
	if x != nil {
		if x, ok := x.StageType.(*AggregationPipelineStage_Project); ok {
			return x.Project
		}
	}
	return nil
}

func (x *AggregationPipelineStage) GetLimit() *LimitStage {
	if x != nil {
		if x, ok := x.StageType.(*AggregationPipelineStage_Limit); ok {
			return x.Limit
		}
	}
	return nil
}

func (x *AggregationPipelineStage) GetSkip() *SkipStage {
	if x != nil {
		if x, ok := x.StageType.(*AggregationPipelineStage_Skip); ok {
			return x.Skip
		}
	}
	return nil
}

func (x *AggregationPipelineStage) GetCount() *CountStage {
	if x != nil {
		if x, ok := x.StageType.(*AggregationPipelineStage_Count); ok {
			return x.Count
		}
	}
	return nil
}

type isAggregationPipelineStage_StageType interface {
	isAggregationPipelineStage_StageType()
}

type AggregationPipelineStage_Match struct {
	Match *MatchStage `protobuf:"bytes,1,opt,name=match,proto3,oneof"`
}

type AggregationPipelineStage_Group struct {
	Group *GroupStage `protobuf:"bytes,2,opt,name=group,proto3,oneof"`
}

type AggregationPipelineStage_Sort struct {
	Sort *SortStage `protobuf:"bytes,3,opt,name=sort,proto3,oneof"`
}

type AggregationPipelineStage_Project struct {
	Project *ProjectStage `protobuf:"bytes,4,opt,name=project,proto3,oneof"`
}

type AggregationPipelineStage_Limit struct {
	Limit *LimitStage `protobuf:"bytes,5,opt,name=limit,proto3,oneof"`
}

type AggregationPipelineStage_Skip struct {
	Skip *SkipStage `protobuf:"bytes,6,opt,name=skip,proto3,oneof"`
}

type AggregationPipelineStage_Count struct {
	Count *CountStage `protobuf:"bytes,7,opt,name=count,proto3,oneof"` // Add more stages like $unwind, $lookup (more complex)
}

func (*AggregationPipelineStage_Match) isAggregationPipelineStage_StageType() {}

func (*AggregationPipelineStage_Group) isAggregationPipelineStage_StageType() {}

func (*AggregationPipelineStage_Sort) isAggregationPipelineStage_StageType() {}

func (*AggregationPipelineStage_Project) isAggregationPipelineStage_StageType() {}

func (*AggregationPipelineStage_Limit) isAggregationPipelineStage_StageType() {}

func (*AggregationPipelineStage_Skip) isAggregationPipelineStage_StageType() {}

func (*AggregationPipelineStage_Count) isAggregationPipelineStage_StageType() {}

// MatchStage: Filters documents (similar to WHERE clause)
type MatchStage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Define filter conditions. Using a simple map for now.
	// Could be a more structured query language (e.g., using google.protobuf.Struct for MongoDB-like queries)
	Filter        map[string]*structpb.Value `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStage) Reset() {
	*x = MatchStage{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStage) ProtoMessage() {}

func (x *MatchStage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStage.ProtoReflect.Descriptor instead.
func (*MatchStage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *MatchStage) GetFilter() map[string]*structpb.Value {
	if x != nil {
		return x.Filter
	}
	return nil
}

// GroupStage: Groups documents by a specified key and applies accumulators.
type GroupStage struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	GroupByField string                 `protobuf:"bytes,1,opt,name=group_by_field,json=groupByField,proto3" json:"group_by_field,omitempty"` // Field to group by (e.g., "$category")
	// Accumulators: field_name_in_output -> {accumulator_type: "$field_to_accumulate_on"}
	Accumulators  map[string]*Accumulator `protobuf:"bytes,2,rep,name=accumulators,proto3" json:"accumulators,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupStage) Reset() {
	*x = GroupStage{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupStage) ProtoMessage() {}

func (x *GroupStage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupStage.ProtoReflect.Descriptor instead.
func (*GroupStage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

func (x *GroupStage) GetGroupByField() string {
	if x != nil {
		return x.GroupByField
	}
	return ""
}

func (x *GroupStage) GetAccumulators() map[string]*Accumulator {
	if x != nil {
		return x.Accumulators
	}
	return nil
}

type Accumulator struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          Accumulator_AccumulatorType `protobuf:"varint,1,opt,name=type,proto3,enum=proto.Accumulator_AccumulatorType" json:"type,omitempty"`
	Field         string                      `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"` // Field to apply accumulator on (e.g., "$price" for $sum). Not needed for COUNT.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accumulator) Reset() {
	*x = Accumulator{}
	mi := &file_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accumulator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accumulator) ProtoMessage() {}

func (x *Accumulator) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accumulator.ProtoReflect.Descriptor instead.
func (*Accumulator) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

func (x *Accumulator) GetType() Accumulator_AccumulatorType {
	if x != nil {
		return x.Type
	}
	return Accumulator_SUM
}

func (x *Accumulator) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

// SortStage: Sorts documents.
type SortStage struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Fields        map[string]SortDirection `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=proto.SortDirection"` // field_name -> direction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortStage) Reset() {
	*x = SortStage{}
	mi := &file_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortStage) ProtoMessage() {}

func (x *SortStage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortStage.ProtoReflect.Descriptor instead.
func (*SortStage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{23}
}

func (x *SortStage) GetFields() map[string]SortDirection {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ProjectStage: Reshapes documents (selects, renames, computes fields).
type ProjectStage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// field_name_in_output -> expression (e.g., "$source_field_name", or computed value)
	// For simplicity: 1 for include, 0 for exclude (like MongoDB).
	// Or map<string, string> for renaming/simple projections: new_name -> "$old_name"
	Fields        map[string]int32 `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 1 to include, 0 to exclude (_id default include unless specified 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectStage) Reset() {
	*x = ProjectStage{}
	mi := &file_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectStage) ProtoMessage() {}

func (x *ProjectStage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectStage.ProtoReflect.Descriptor instead.
func (*ProjectStage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{24}
}

func (x *ProjectStage) GetFields() map[string]int32 {
	if x != nil {
		return x.Fields
	}
	return nil
}

type LimitStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimitStage) Reset() {
	*x = LimitStage{}
	mi := &file_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimitStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitStage) ProtoMessage() {}

func (x *LimitStage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitStage.ProtoReflect.Descriptor instead.
func (*LimitStage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{25}
}

func (x *LimitStage) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SkipStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipStage) Reset() {
	*x = SkipStage{}
	mi := &file_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipStage) ProtoMessage() {}

func (x *SkipStage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipStage.ProtoReflect.Descriptor instead.
func (*SkipStage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{26}
}

func (x *SkipStage) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CountStage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OutputFieldName string                 `protobuf:"bytes,1,opt,name=output_field_name,json=outputFieldName,proto3" json:"output_field_name,omitempty"` // Field name for the count result
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CountStage) Reset() {
	*x = CountStage{}
	mi := &file_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountStage) ProtoMessage() {}

func (x *CountStage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountStage.ProtoReflect.Descriptor instead.
func (*CountStage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{27}
}

func (x *CountStage) GetOutputFieldName() string {
	if x != nil {
		return x.OutputFieldName
	}
	return ""
}

type AggregationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Results can be a list of documents or aggregated values.
	// Using google.protobuf.Struct to represent flexible result documents.
	Results       []*structpb.Struct `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Success       bool               `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string             `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Optional message, e.g., error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregationResponse) Reset() {
	*x = AggregationResponse{}
	mi := &file_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationResponse) ProtoMessage() {}

func (x *AggregationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationResponse.ProtoReflect.Descriptor instead.
func (*AggregationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{28}
}

func (x *AggregationResponse) GetResults() []*structpb.Struct {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *AggregationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AggregationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x05proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x01\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x129\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1d.proto.Document.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\bGeoPoint\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"j\n" +
	"\bGeoShape\x12*\n" +
	"\btop_left\x18\x01 \x01(\v2\x0f.proto.GeoPointR\atopLeft\x122\n" +
	"\fbottom_right\x18\x02 \x01(\v2\x0f.proto.GeoPointR\vbottomRight\"c\n" +
	"\vWriteResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x10\n" +
	"\x03lsn\x18\x04 \x01(\tR\x03lsn\"n\n" +
	"\x13IndexedWriteRequest\x12+\n" +
	"\bdocument\x18\x01 \x01(\v2\x0f.proto.DocumentR\bdocument\x12*\n" +
	"\x11indexes_to_update\x18\x02 \x03(\tR\x0findexesToUpdate\"\xd0\x01\n" +
	"\x1aUpdateInvertedIndexRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12R\n" +
	"\vtext_fields\x18\x02 \x03(\v21.proto.UpdateInvertedIndexRequest.TextFieldsEntryR\n" +
	"textFields\x1a=\n" +
	"\x0fTextFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x02\n" +
	"\x19UpdateSpatialIndexRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12%\n" +
	"\x05shape\x18\x02 \x01(\v2\x0f.proto.GeoShapeR\x05shape\x12P\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v20.proto.UpdateSpatialIndexRequest.AttributesEntryR\n" +
	"attributes\x1aU\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"8\n" +
	"\x15DeleteDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"5\n" +
	"\x12GetDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"X\n" +
	"\x13GetDocumentResponse\x12+\n" +
	"\bdocument\x18\x01 \x01(\v2\x0f.proto.DocumentR\bdocument\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x8a\x01\n" +
	"\x1aSearchInvertedIndexRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12(\n" +
	"\x10fields_to_search\x18\x04 \x03(\tR\x0efieldsToSearch\"\xb3\x01\n" +
	"\x19SearchSpatialIndexRequest\x120\n" +
	"\vquery_shape\x18\x01 \x01(\v2\x0f.proto.GeoShapeR\n" +
	"queryShape\x126\n" +
	"\n" +
	"query_type\x18\x02 \x01(\x0e2\x17.proto.SpatialQueryTypeR\tqueryType\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"^\n" +
	"\x0eSearchResponse\x12-\n" +
	"\tdocuments\x18\x01 \x03(\v2\x0f.proto.DocumentR\tdocuments\x12\x1d\n" +
	"\n" +
	"total_hits\x18\x02 \x01(\x03R\ttotalHits\"^\n" +
	"\x10RangeScanRequest\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\tR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\tR\x06endKey\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"y\n" +
	"\rBulkOperation\x12;\n" +
	"\x0eoperation_type\x18\x01 \x01(\x0e2\x14.proto.OperationTypeR\roperationType\x12+\n" +
	"\bdocument\x18\x02 \x01(\v2\x0f.proto.DocumentR\bdocument\"H\n" +
	"\x10BulkWriteRequest\x124\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x14.proto.BulkOperationR\n" +
	"operations\"\x8b\x01\n" +
	"\x11BulkWriteResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.proto.WriteResultR\aresults\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x03 \x01(\x05R\ffailureCount\"\xf1\x01\n" +
	"\x18BulkWriteSummaryResponse\x12)\n" +
	"\x10total_operations\x18\x01 \x01(\x05R\x0ftotalOperations\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x03 \x01(\x05R\ffailureCount\x120\n" +
	"\x14failed_operation_ids\x18\x04 \x03(\tR\x12failedOperationIds\x12.\n" +
	"\x13first_error_message\x18\x05 \x01(\tR\x11firstErrorMessage\"v\n" +
	"\x12AggregationRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x127\n" +
	"\x06stages\x18\x02 \x03(\v2\x1f.proto.AggregationPipelineStageR\x06stages\"\xd5\x02\n" +
	"\x18AggregationPipelineStage\x12)\n" +
	"\x05match\x18\x01 \x01(\v2\x11.proto.MatchStageH\x00R\x05match\x12)\n" +
	"\x05group\x18\x02 \x01(\v2\x11.proto.GroupStageH\x00R\x05group\x12&\n" +
	"\x04sort\x18\x03 \x01(\v2\x10.proto.SortStageH\x00R\x04sort\x12/\n" +
	"\aproject\x18\x04 \x01(\v2\x13.proto.ProjectStageH\x00R\aproject\x12)\n" +
	"\x05limit\x18\x05 \x01(\v2\x11.proto.LimitStageH\x00R\x05limit\x12&\n" +
	"\x04skip\x18\x06 \x01(\v2\x10.proto.SkipStageH\x00R\x04skip\x12)\n" +
	"\x05count\x18\a \x01(\v2\x11.proto.CountStageH\x00R\x05countB\f\n" +
	"\n" +
	"stage_type\"\x96\x01\n" +
	"\n" +
	"MatchStage\x125\n" +
	"\x06filter\x18\x01 \x03(\v2\x1d.proto.MatchStage.FilterEntryR\x06filter\x1aQ\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xd0\x01\n" +
	"\n" +
	"GroupStage\x12$\n" +
	"\x0egroup_by_field\x18\x01 \x01(\tR\fgroupByField\x12G\n" +
	"\faccumulators\x18\x02 \x03(\v2#.proto.GroupStage.AccumulatorsEntryR\faccumulators\x1aS\n" +
	"\x11AccumulatorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.proto.AccumulatorR\x05value:\x028\x01\"\xbc\x01\n" +
	"\vAccumulator\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".proto.Accumulator.AccumulatorTypeR\x04type\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"_\n" +
	"\x0fAccumulatorType\x12\a\n" +
	"\x03SUM\x10\x00\x12\a\n" +
	"\x03AVG\x10\x01\x12\a\n" +
	"\x03MIN\x10\x02\x12\a\n" +
	"\x03MAX\x10\x03\x12\t\n" +
	"\x05COUNT\x10\x04\x12\t\n" +
	"\x05FIRST\x10\x05\x12\b\n" +
	"\x04LAST\x10\x06\x12\b\n" +
	"\x04PUSH\x10\a\"\x92\x01\n" +
	"\tSortStage\x124\n" +
	"\x06fields\x18\x01 \x03(\v2\x1c.proto.SortStage.FieldsEntryR\x06fields\x1aO\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\x0e2\x14.proto.SortDirectionR\x05value:\x028\x01\"\x82\x01\n" +
	"\fProjectStage\x127\n" +
	"\x06fields\x18\x01 \x03(\v2\x1f.proto.ProjectStage.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\"\n" +
	"\n" +
	"LimitStage\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"!\n" +
	"\tSkipStage\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"8\n" +
	"\n" +
	"CountStage\x12*\n" +
	"\x11output_field_name\x18\x01 \x01(\tR\x0foutputFieldName\"|\n" +
	"\x13AggregationResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.google.protobuf.StructR\aresults\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*<\n" +
	"\x10SpatialQueryType\x12\x0e\n" +
	"\n" +
	"INTERSECTS\x10\x00\x12\f\n" +
	"\bCONTAINS\x10\x01\x12\n" +
	"\n" +
	"\x06WITHIN\x10\x02*'\n" +
	"\rOperationType\x12\n" +
	"\n" +
	"\x06UPSERT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01*\"\n" +
	"\rSortDirection\x12\a\n" +
	"\x03ASC\x10\x00\x12\b\n" +
	"\x04DESC\x10\x012\xb3\x02\n" +
	"\x13IndexedWriteService\x12>\n" +
	"\fIndexedWrite\x12\x1a.proto.IndexedWriteRequest\x1a\x12.proto.WriteResult\x12L\n" +
	"\x13UpdateInvertedIndex\x12!.proto.UpdateInvertedIndexRequest\x1a\x12.proto.WriteResult\x12J\n" +
	"\x12UpdateSpatialIndex\x12 .proto.UpdateSpatialIndexRequest\x1a\x12.proto.WriteResult\x12B\n" +
	"\x0eDeleteDocument\x12\x1c.proto.DeleteDocumentRequest\x1a\x12.proto.WriteResult2\xb3\x02\n" +
	"\x12IndexedReadService\x12D\n" +
	"\vGetDocument\x12\x19.proto.GetDocumentRequest\x1a\x1a.proto.GetDocumentResponse\x12O\n" +
	"\x13SearchInvertedIndex\x12!.proto.SearchInvertedIndexRequest\x1a\x15.proto.SearchResponse\x12M\n" +
	"\x12SearchSpatialIndex\x12 .proto.SearchSpatialIndexRequest\x1a\x15.proto.SearchResponse\x127\n" +
	"\tRangeScan\x12\x17.proto.RangeScanRequest\x1a\x0f.proto.Document0\x012\x9e\x01\n" +
	"\x10BulkWriteService\x12>\n" +
	"\tBulkWrite\x12\x17.proto.BulkWriteRequest\x1a\x18.proto.BulkWriteResponse\x12J\n" +
	"\x0fStreamBulkWrite\x12\x14.proto.BulkOperation\x1a\x1f.proto.BulkWriteSummaryResponse(\x012X\n" +
	"\x12AggregationService\x12B\n" +
	"\tAggregate\x12\x19.proto.AggregationRequest\x1a\x1a.proto.AggregationResponseB)Z'github.com/sushant-115/gojodb/api/protob\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_api_proto_goTypes = []any{
	(SpatialQueryType)(0),              // 0: proto.SpatialQueryType
	(OperationType)(0),                 // 1: proto.OperationType
	(SortDirection)(0),                 // 2: proto.SortDirection
	(Accumulator_AccumulatorType)(0),   // 3: proto.Accumulator.AccumulatorType
	(*Document)(nil),                   // 4: proto.Document
	(*GeoPoint)(nil),                   // 5: proto.GeoPoint
	(*GeoShape)(nil),                   // 6: proto.GeoShape
	(*WriteResult)(nil),                // 7: proto.WriteResult
	(*IndexedWriteRequest)(nil),        // 8: proto.IndexedWriteRequest
	(*UpdateInvertedIndexRequest)(nil), // 9: proto.UpdateInvertedIndexRequest
	(*UpdateSpatialIndexRequest)(nil),  // 10: proto.UpdateSpatialIndexRequest
	(*DeleteDocumentRequest)(nil),      // 11: proto.DeleteDocumentRequest
	(*GetDocumentRequest)(nil),         // 12: proto.GetDocumentRequest
	(*GetDocumentResponse)(nil),        // 13: proto.GetDocumentResponse
	(*SearchInvertedIndexRequest)(nil), // 14: proto.SearchInvertedIndexRequest
	(*SearchSpatialIndexRequest)(nil),  // 15: proto.SearchSpatialIndexRequest
	(*SearchResponse)(nil),             // 16: proto.SearchResponse
	(*RangeScanRequest)(nil),           // 17: proto.RangeScanRequest
	(*BulkOperation)(nil),              // 18: proto.BulkOperation
	(*BulkWriteRequest)(nil),           // 19: proto.BulkWriteRequest
	(*BulkWriteResponse)(nil),          // 20: proto.BulkWriteResponse
	(*BulkWriteSummaryResponse)(nil),   // 21: proto.BulkWriteSummaryResponse
	(*AggregationRequest)(nil),         // 22: proto.AggregationRequest
	(*AggregationPipelineStage)(nil),   // 23: proto.AggregationPipelineStage
	(*MatchStage)(nil),                 // 24: proto.MatchStage
	(*GroupStage)(nil),                 // 25: proto.GroupStage
	(*Accumulator)(nil),                // 26: proto.Accumulator
	(*SortStage)(nil),                  // 27: proto.SortStage
	(*ProjectStage)(nil),               // 28: proto.ProjectStage
	(*LimitStage)(nil),                 // 29: proto.LimitStage
	(*SkipStage)(nil),                  // 30: proto.SkipStage
	(*CountStage)(nil),                 // 31: proto.CountStage
	(*AggregationResponse)(nil),        // 32: proto.AggregationResponse
	nil,                                // 33: proto.Document.MetadataEntry
	nil,                                // 34: proto.UpdateInvertedIndexRequest.TextFieldsEntry
	nil,                                // 35: proto.UpdateSpatialIndexRequest.AttributesEntry
	nil,                                // 36: proto.MatchStage.FilterEntry
	nil,                                // 37: proto.GroupStage.AccumulatorsEntry
	nil,                                // 38: proto.SortStage.FieldsEntry
	nil,                                // 39: proto.ProjectStage.FieldsEntry
	(*structpb.Struct)(nil),            // 40: google.protobuf.Struct
	(*structpb.Value)(nil),             // 41: google.protobuf.Value
}
var file_api_proto_depIdxs = []int32{
	40, // 0: proto.Document.data:type_name -> google.protobuf.Struct
	33, // 1: proto.Document.metadata:type_name -> proto.Document.MetadataEntry
	5,  // 2: proto.GeoShape.top_left:type_name -> proto.GeoPoint
	5,  // 3: proto.GeoShape.bottom_right:type_name -> proto.GeoPoint
	4,  // 4: proto.IndexedWriteRequest.document:type_name -> proto.Document
	34, // 5: proto.UpdateInvertedIndexRequest.text_fields:type_name -> proto.UpdateInvertedIndexRequest.TextFieldsEntry
	6,  // 6: proto.UpdateSpatialIndexRequest.shape:type_name -> proto.GeoShape
	35, // 7: proto.UpdateSpatialIndexRequest.attributes:type_name -> proto.UpdateSpatialIndexRequest.AttributesEntry
	4,  // 8: proto.GetDocumentResponse.document:type_name -> proto.Document
	6,  // 9: proto.SearchSpatialIndexRequest.query_shape:type_name -> proto.GeoShape
	0,  // 10: proto.SearchSpatialIndexRequest.query_type:type_name -> proto.SpatialQueryType
	4,  // 11: proto.SearchResponse.documents:type_name -> proto.Document
	1,  // 12: proto.BulkOperation.operation_type:type_name -> proto.OperationType
	4,  // 13: proto.BulkOperation.document:type_name -> proto.Document
	18, // 14: proto.BulkWriteRequest.operations:type_name -> proto.BulkOperation
	7,  // 15: proto.BulkWriteResponse.results:type_name -> proto.WriteResult
	23, // 16: proto.AggregationRequest.stages:type_name -> proto.AggregationPipelineStage
	24, // 17: proto.AggregationPipelineStage.match:type_name -> proto.MatchStage
	25, // 18: proto.AggregationPipelineStage.group:type_name -> proto.GroupStage
	27, // 19: proto.AggregationPipelineStage.sort:type_name -> proto.SortStage
	28, // 20: proto.AggregationPipelineStage.project:type_name -> proto.ProjectStage
	29, // 21: proto.AggregationPipelineStage.limit:type_name -> proto.LimitStage
	30, // 22: proto.AggregationPipelineStage.skip:type_name -> proto.SkipStage
	31, // 23: proto.AggregationPipelineStage.count:type_name -> proto.CountStage
	36, // 24: proto.MatchStage.filter:type_name -> proto.MatchStage.FilterEntry
	37, // 25: proto.GroupStage.accumulators:type_name -> proto.GroupStage.AccumulatorsEntry
	3,  // 26: proto.Accumulator.type:type_name -> proto.Accumulator.AccumulatorType
	38, // 27: proto.SortStage.fields:type_name -> proto.SortStage.FieldsEntry
	39, // 28: proto.ProjectStage.fields:type_name -> proto.ProjectStage.FieldsEntry
	40, // 29: proto.AggregationResponse.results:type_name -> google.protobuf.Struct
	41, // 30: proto.UpdateSpatialIndexRequest.AttributesEntry.value:type_name -> google.protobuf.Value
	41, // 31: proto.MatchStage.FilterEntry.value:type_name -> google.protobuf.Value
	26, // 32: proto.GroupStage.AccumulatorsEntry.value:type_name -> proto.Accumulator
	2,  // 33: proto.SortStage.FieldsEntry.value:type_name -> proto.SortDirection
	8,  // 34: proto.IndexedWriteService.IndexedWrite:input_type -> proto.IndexedWriteRequest
	9,  // 35: proto.IndexedWriteService.UpdateInvertedIndex:input_type -> proto.UpdateInvertedIndexRequest
	10, // 36: proto.IndexedWriteService.UpdateSpatialIndex:input_type -> proto.UpdateSpatialIndexRequest
	11, // 37: proto.IndexedWriteService.DeleteDocument:input_type -> proto.DeleteDocumentRequest
	12, // 38: proto.IndexedReadService.GetDocument:input_type -> proto.GetDocumentRequest
	14, // 39: proto.IndexedReadService.SearchInvertedIndex:input_type -> proto.SearchInvertedIndexRequest
	15, // 40: proto.IndexedReadService.SearchSpatialIndex:input_type -> proto.SearchSpatialIndexRequest
	17, // 41: proto.IndexedReadService.RangeScan:input_type -> proto.RangeScanRequest
	19, // 42: proto.BulkWriteService.BulkWrite:input_type -> proto.BulkWriteRequest
	18, // 43: proto.BulkWriteService.StreamBulkWrite:input_type -> proto.BulkOperation
	22, // 44: proto.AggregationService.Aggregate:input_type -> proto.AggregationRequest
	7,  // 45: proto.IndexedWriteService.IndexedWrite:output_type -> proto.WriteResult
	7,  // 46: proto.IndexedWriteService.UpdateInvertedIndex:output_type -> proto.WriteResult
	7,  // 47: proto.IndexedWriteService.UpdateSpatialIndex:output_type -> proto.WriteResult
	7,  // 48: proto.IndexedWriteService.DeleteDocument:output_type -> proto.WriteResult
	13, // 49: proto.IndexedReadService.GetDocument:output_type -> proto.GetDocumentResponse
	16, // 50: proto.IndexedReadService.SearchInvertedIndex:output_type -> proto.SearchResponse
	16, // 51: proto.IndexedReadService.SearchSpatialIndex:output_type -> proto.SearchResponse
	4,  // 52: proto.IndexedReadService.RangeScan:output_type -> proto.Document
	20, // 53: proto.BulkWriteService.BulkWrite:output_type -> proto.BulkWriteResponse
	21, // 54: proto.BulkWriteService.StreamBulkWrite:output_type -> proto.BulkWriteSummaryResponse
	32, // 55: proto.AggregationService.Aggregate:output_type -> proto.AggregationResponse
	45, // [45:56] is the sub-list for method output_type
	34, // [34:45] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[19].OneofWrappers = []any{
		(*AggregationPipelineStage_Match)(nil),
		(*AggregationPipelineStage_Group)(nil),
		(*AggregationPipelineStage_Sort)(nil),
		(*AggregationPipelineStage_Project)(nil),
		(*AggregationPipelineStage_Limit)(nil),
		(*AggregationPipelineStage_Skip)(nil),
		(*AggregationPipelineStage_Count)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
