package parser
// Package parser implements a lexer and recursive-descent parser for GojoDB's
// query language (GQL) – a SQL-like dialect tailored to key-value, full-text,
// and spatial index operations.
//
// Supported statements:
//
//	SELECT key [, value] FROM <index> [WHERE <pred>] [ORDER BY key [ASC|DESC]] [LIMIT n]


























































































































































































































































































































































































































































































































































































































































































































































































































































































































}	return strconv.ParseFloat(tok.Literal, 64)	p.next()	}		return 0, fmt.Errorf("expected number, got %q at pos %d", tok.Literal, tok.Pos)	if tok.Type != TOKEN_NUMBER {	tok := p.currentfunc (p *Parser) parseFloat() (float64, error) {}	}, nil		MaxLat: coords[2], MaxLon: coords[3],		MinLat: coords[0], MinLon: coords[1],	return &WithinPredicate{	}		return nil, err	if _, err = p.expect(TOKEN_RPAREN); err != nil {	}		}			return nil, err		if err != nil {		coords[i], err = p.parseFloat()		}			return nil, err		if _, err = p.expect(TOKEN_COMMA); err != nil {	for i := 1; i < 4; i++ {	coords := [4]float64{minLat}	}		_ = v	}{{&minLat, "minLat"}} {		name string		ptr  *float64	for _, v := range []struct {	}		return nil, err	if err != nil {	minLat, err := p.parseFloat()	}		return nil, err	if _, err := p.expect(TOKEN_LPAREN); err != nil {	p.next() // consume WITHINfunc (p *Parser) parseWithin() (*WithinPredicate, error) {}	return &NearPredicate{Lat: lat, Lon: lon, Radius: radius}, nil	}		return nil, err	if _, err = p.expect(TOKEN_RPAREN); err != nil {	}		return nil, fmt.Errorf("NEAR: radius: %w", err)	if err != nil {	radius, err := p.parseFloat()	}		return nil, err	if _, err = p.expect(TOKEN_COMMA); err != nil {	}		return nil, fmt.Errorf("NEAR: lon: %w", err)	if err != nil {	lon, err := p.parseFloat()	}		return nil, err	if _, err = p.expect(TOKEN_COMMA); err != nil {	}		return nil, fmt.Errorf("NEAR: lat: %w", err)	if err != nil {	lat, err := p.parseFloat()	}		return nil, err	if _, err := p.expect(TOKEN_LPAREN); err != nil {	p.next() // consume NEARfunc (p *Parser) parseNear() (*NearPredicate, error) {}	return &TextSearchPredicate{Field: fieldTok.Literal, Query: queryTok.Literal}, nil	}		return nil, err	if _, err = p.expect(TOKEN_RPAREN); err != nil {	}		return nil, err	if err != nil {	queryTok, err := p.expect(TOKEN_STRING)	}		return nil, err	if _, err = p.expect(TOKEN_COMMA); err != nil {	}		return nil, err	if err != nil {	fieldTok, err := p.expectIdent()	}		return nil, err	if _, err := p.expect(TOKEN_LPAREN); err != nil {	p.next() // consume CONTAINSfunc (p *Parser) parseContains() (*TextSearchPredicate, error) {}	return t, fmt.Errorf("expected string or identifier, got %q at pos %d", t.Literal, t.Pos)	}		return t, nil		p.next()	if t.Type == TOKEN_STRING || t.Type == TOKEN_IDENT || t.Type == TOKEN_NUMBER {	t := p.currentfunc (p *Parser) expectStringOrIdent() (Token, error) {}	return nil, fmt.Errorf("unexpected token %q after field name at pos %d", p.current.Literal, p.current.Pos)	}		return &CompPredicate{Field: fieldTok.Literal, Op: op, Value: valTok.Literal}, nil		}			return nil, valErr		if valErr != nil {		valTok, valErr := p.expectStringOrIdent()		p.next()		op := p.current.Type	case TOKEN_NEQ, TOKEN_LT, TOKEN_LTE, TOKEN_GT, TOKEN_GTE:		return &EqPredicate{Field: fieldTok.Literal, Value: valTok.Literal}, nil		}			return nil, valErr		if valErr != nil {		valTok, valErr := p.expectStringOrIdent()		p.next()	case TOKEN_EQ:		}, nil			EndKey:   endTok.Literal,			StartKey: startTok.Literal,			Field:    fieldTok.Literal,		return &RangePredicate{		}			return nil, endErr		if endErr != nil {		endTok, endErr := p.expect(TOKEN_STRING)		}			return nil, err		if _, err = p.expect(TOKEN_AND); err != nil {		}			return nil, startErr		if startErr != nil {		startTok, startErr := p.expect(TOKEN_STRING)		p.next()	case TOKEN_BETWEEN:	switch p.current.Type {	}		return nil, err	if err != nil {	fieldTok, err := p.expectIdent()	// field <op> value  or  field BETWEEN a AND b	}		return p.parseWithin()	if p.current.Type == TOKEN_WITHIN {	// WITHIN(minLat, minLon, maxLat, maxLon)	}		return p.parseNear()	if p.current.Type == TOKEN_NEAR {	// NEAR(lat, lon, radius)	}		return p.parseContains()	if p.current.Type == TOKEN_CONTAINS {	// CONTAINS(field, 'query')	}		return pred, nil		}			return nil, err		if _, err = p.expect(TOKEN_RPAREN); err != nil {		}			return nil, err		if err != nil {		pred, err := p.parsePredicate()		p.next()	if p.current.Type == TOKEN_LPAREN {	// Grouped predicatefunc (p *Parser) parseAtomPred() (Predicate, error) {}	return p.parseAtomPred()	}		return &NotPredicate{Pred: pred}, nil		}			return nil, err		if err != nil {		pred, err := p.parseAtomPred()		p.next()	if p.current.Type == TOKEN_NOT {func (p *Parser) parseNotPred() (Predicate, error) {}	return left, nil	}		left = &AndPredicate{Left: left, Right: right}		}			return nil, rightErr		if rightErr != nil {		right, rightErr := p.parseNotPred()		p.next()	for p.current.Type == TOKEN_AND {	}		return nil, err	if err != nil {	left, err := p.parseNotPred()func (p *Parser) parseAndPred() (Predicate, error) {}	return left, nil	}		left = &OrPredicate{Left: left, Right: right}		}			return nil, rightErr		if rightErr != nil {		right, rightErr := p.parseAndPred()		p.next()	for p.current.Type == TOKEN_OR {	}		return nil, err	if err != nil {	left, err := p.parseAndPred()func (p *Parser) parseOrPred() (Predicate, error) {}	return p.parseOrPred()func (p *Parser) parsePredicate() (Predicate, error) {// -----------------------------------------------------------------------// Predicate parsing  (precedence: OR < AND < NOT < atom)// -----------------------------------------------------------------------}	return stmt, nil	}		stmt.Where = pred		}			return nil, predErr		if predErr != nil {		pred, predErr := p.parsePredicate()		p.next()	if p.current.Type == TOKEN_WHERE {	stmt := &UpdateStmt{IndexName: indexTok.Literal, Value: valTok.Literal}	}		return nil, err	if err != nil {	valTok, err := p.expect(TOKEN_STRING)	}		return nil, err	if _, err = p.expect(TOKEN_EQ); err != nil {	}		return nil, err	if _, err = p.expect(TOKEN_IDENT); err != nil { // column name	// SET value = '...'	}		return nil, err	if _, err = p.expect(TOKEN_SET); err != nil {	}		return nil, err	if err != nil {	indexTok, err := p.expectIdent()	p.next() // consume UPDATEfunc (p *Parser) parseUpdate() (*UpdateStmt, error) {}	return stmt, nil	}		stmt.Where = pred		}			return nil, predErr		if predErr != nil {		pred, predErr := p.parsePredicate()		p.next()	if p.current.Type == TOKEN_WHERE {	stmt := &DeleteStmt{IndexName: indexTok.Literal}	}		return nil, err	if err != nil {	indexTok, err := p.expectIdent()	}		return nil, err	if _, err := p.expect(TOKEN_FROM); err != nil {	p.next() // consume DELETEfunc (p *Parser) parseDelete() (*DeleteStmt, error) {}	}, nil		Value:     valTok.Literal,		Key:       keyTok.Literal,		IndexName: indexTok.Literal,	return &InsertStmt{	}		return nil, err	if _, err = p.expect(TOKEN_RPAREN); err != nil {	}		return nil, err	if err != nil {	valTok, err := p.expect(TOKEN_STRING)	}		return nil, err	if _, err = p.expect(TOKEN_COMMA); err != nil {	}		return nil, err	if err != nil {	keyTok, err := p.expect(TOKEN_STRING)	}		return nil, err	if _, err = p.expect(TOKEN_LPAREN); err != nil {	}		return nil, err	if _, err = p.expect(TOKEN_VALUES); err != nil {	// VALUES	}		return nil, err	if _, err = p.expect(TOKEN_RPAREN); err != nil {	}		return nil, err	if _, err = p.expect(TOKEN_IDENT); err != nil { // 'value' column label	}		return nil, err	if _, err = p.expect(TOKEN_COMMA); err != nil {	}		return nil, err	if _, err = p.expect(TOKEN_IDENT); err != nil { // 'key' column label	}		return nil, err	if _, err = p.expect(TOKEN_LPAREN); err != nil {	// (key, value)	}		return nil, err	if err != nil {	indexTok, err := p.expectIdent()	}		return nil, err	if _, err := p.expect(TOKEN_INTO); err != nil {	p.next() // consume INSERTfunc (p *Parser) parseInsert() (*InsertStmt, error) {}	return cols, nil	}		p.next() // consume comma		}			break		if p.current.Type != TOKEN_COMMA {		cols = append(cols, tok.Literal)		}			return nil, err		if err != nil {		tok, err := p.expectIdent()	for {	var cols []string	}		return []string{"*"}, nil		p.next()	if p.current.Type == TOKEN_STAR {func (p *Parser) parseColumnList() ([]string, error) {}	return stmt, nil	}		stmt.Limit = int32(n)		}			return nil, fmt.Errorf("invalid LIMIT value: %s", numTok.Literal)		if parseErr != nil {		n, parseErr := strconv.ParseInt(numTok.Literal, 10, 32)		}			return nil, numErr		if numErr != nil {		numTok, numErr := p.expect(TOKEN_NUMBER)		p.next()	if p.current.Type == TOKEN_LIMIT {	// Optional LIMIT	}		stmt.OrderBy = ob		}			p.next()		} else if p.current.Type == TOKEN_ASC {			p.next()			ob.Desc = true		if p.current.Type == TOKEN_DESC {		ob := &OrderBy{Field: fieldTok.Literal}		}			return nil, fieldErr		if fieldErr != nil {		fieldTok, fieldErr := p.expectIdent()		}			return nil, err		if _, err = p.expect(TOKEN_BY); err != nil {		p.next()	if p.current.Type == TOKEN_ORDER {	// Optional ORDER BY	}		stmt.Where = pred		}			return nil, predErr		if predErr != nil {		pred, predErr := p.parsePredicate()		p.next()	if p.current.Type == TOKEN_WHERE {	// Optional WHERE	stmt := &SelectStmt{Columns: cols, IndexName: indexToken.Literal}	}		return nil, err	if err != nil {	indexToken, err := p.expectIdent()	}		return nil, err	if _, err = p.expect(TOKEN_FROM); err != nil {	// FROM <index>	}		return nil, err	if err != nil {	cols, err := p.parseColumnList()	// Column list	p.next() // consume SELECTfunc (p *Parser) parseSelect() (*SelectStmt, error) {// -----------------------------------------------------------------------// Statement parsers// -----------------------------------------------------------------------}	return NewParser(strings.TrimSpace(query)).Parse()func Parse(query string) (Statement, error) {// Parse parses a query string into a Statement.}	}		return nil, fmt.Errorf("unexpected token %q at pos %d", p.current.Literal, p.current.Pos)	default:		return p.parseUpdate()	case TOKEN_UPDATE:		return p.parseDelete()	case TOKEN_DELETE:		return p.parseInsert()	case TOKEN_INSERT:		return p.parseSelect()	case TOKEN_SELECT:	switch p.current.Type {func (p *Parser) Parse() (Statement, error) {// Parse parses a single statement from the input.}	return t, nil	p.next()	}		return t, fmt.Errorf("expected identifier, got %d (%q) at pos %d", t.Type, t.Literal, t.Pos)	if t.Type != TOKEN_IDENT && t.Type < TOKEN_SELECT {	// Accept both identifiers and keywords used as column/index names.	t := p.currentfunc (p *Parser) expectIdent() (Token, error) {}	return t, nil	p.next()	}		return t, fmt.Errorf("expected token %d, got %d (%q) at pos %d", tt, t.Type, t.Literal, t.Pos)	if t.Type != tt {	t := p.currentfunc (p *Parser) expect(tt TokenType) (Token, error) {}	return p.peeked	}		p.hasPeek = true		p.peeked = p.lexer.NextToken()	if !p.hasPeek {func (p *Parser) peek() Token {}	return p.current	}		p.current = p.lexer.NextToken()	} else {		p.hasPeek = false		p.current = p.peeked	if p.hasPeek {func (p *Parser) next() Token {}	return p	p.current = p.lexer.NextToken()	p := &Parser{lexer: NewLexer(query)}func NewParser(query string) *Parser {// NewParser creates a Parser for the given query string.}	hasPeek bool	peeked  Token	current Token	lexer   *Lexertype Parser struct {// Parser implements recursive-descent parsing of GQL statements.// -----------------------------------------------------------------------// Parser// -----------------------------------------------------------------------func (*NotPredicate) predNode() {}}	Pred Predicatetype NotPredicate struct {// NotPredicate: NOT predfunc (*OrPredicate) predNode() {}}	Left, Right Predicatetype OrPredicate struct {// OrPredicate: left OR rightfunc (*AndPredicate) predNode() {}}	Left, Right Predicatetype AndPredicate struct {// AndPredicate: left AND rightfunc (*WithinPredicate) predNode() {}}	MaxLat, MaxLon float64	MinLat, MinLon float64type WithinPredicate struct {// WithinPredicate: WITHIN(minLat, minLon, maxLat, maxLon)func (*NearPredicate) predNode() {}}	Radius float64	Lon    float64	Lat    float64type NearPredicate struct {// NearPredicate: NEAR(lat, lon, radiusMetres)func (*TextSearchPredicate) predNode() {}}	Query string	Field stringtype TextSearchPredicate struct {// TextSearchPredicate: CONTAINS(field, 'query')func (*CompPredicate) predNode() {}}	Value string	Op    TokenType	Field stringtype CompPredicate struct {// CompPredicate: field <op> 'value'   (for <, <=, >, >=, !=)func (*RangePredicate) predNode() {}}	EndKey   string	StartKey string	Field    stringtype RangePredicate struct {// RangePredicate: key BETWEEN 'a' AND 'b'func (*EqPredicate) predNode() {}}	Value string	Field stringtype EqPredicate struct {// EqPredicate: key = 'value'}	predNode()type Predicate interface {// Predicate is any expression that yields a boolean.// -----------------------------------------------------------------------// Predicate node types// -----------------------------------------------------------------------}	Desc  bool	Field stringtype OrderBy struct {// OrderBy captures the ORDER BY clause.func (*UpdateStmt) stmtNode() {}}	Where     Predicate	Value     string	IndexName stringtype UpdateStmt struct {// UpdateStmt represents: UPDATE <index> SET value = 'v' WHERE key = 'k'func (*DeleteStmt) stmtNode() {}}	Where     Predicate	IndexName stringtype DeleteStmt struct {// DeleteStmt represents: DELETE FROM <index> WHERE key = 'k'func (*InsertStmt) stmtNode() {}}	Value     string	Key       string	IndexName stringtype InsertStmt struct {// InsertStmt represents: INSERT INTO <index> (key, value) VALUES ('k', 'v')func (*SelectStmt) stmtNode() {}}	Limit     int32 // 0 = no limit	OrderBy   *OrderBy	Where     Predicate // nil = no filter	IndexName string	Columns   []string   // nil / ["*"] means alltype SelectStmt struct {// SelectStmt represents: SELECT <columns> FROM <index> [WHERE pred] [ORDER BY ...] [LIMIT n]}	stmtNode()type Statement interface {// Statement is the top-level AST node.// -----------------------------------------------------------------------// AST node types// -----------------------------------------------------------------------}	return tokens	}		tokens = append(tokens, t)		}			break		if t.Type == TOKEN_EOF {		t := l.NextToken()	for {	var tokens []Token	l := NewLexer(input)func Tokenize(input string) []Token {// Tokenize returns all tokens (excluding EOF) for the given input.}	return Token{Type: TOKEN_NUMBER, Literal: string(l.input[start:l.pos]), Pos: start}	}		l.pos++	for l.pos < len(l.input) && (unicode.IsDigit(l.input[l.pos]) || l.input[l.pos] == '.') {func (l *Lexer) readNumber(start int) Token {}	return Token{Type: TOKEN_IDENT, Literal: string(l.input[start:l.pos]), Pos: start}	}		return Token{Type: tt, Literal: lit, Pos: start}	if tt, ok := keywords[lit]; ok {	lit := strings.ToUpper(string(l.input[start:l.pos]))	}		l.pos++	for l.pos < len(l.input) && (unicode.IsLetter(l.input[l.pos]) || unicode.IsDigit(l.input[l.pos]) || l.input[l.pos] == '_') {func (l *Lexer) readIdent(start int) Token {}	return Token{Type: TOKEN_ILLEGAL, Literal: sb.String(), Pos: start} // unterminated	}		sb.WriteRune(ch)		}			return Token{Type: TOKEN_STRING, Literal: sb.String(), Pos: start}			}				continue				sb.WriteRune('\'')				l.advance()				// Escaped single-quote '' → single '			if l.pos < len(l.input) && l.peek() == '\'' {		if ch == '\'' {		ch := l.advance()	for l.pos < len(l.input) {	var sb strings.Builderfunc (l *Lexer) readString(start int) Token {}	}		return Token{Type: TOKEN_ILLEGAL, Literal: string(ch), Pos: start}	default:		return Token{Type: TOKEN_STAR, Literal: "*", Pos: start}	case ch == '*':		return Token{Type: TOKEN_RPAREN, Literal: ")", Pos: start}	case ch == ')':		return Token{Type: TOKEN_LPAREN, Literal: "(", Pos: start}	case ch == '(':		return Token{Type: TOKEN_COMMA, Literal: ",", Pos: start}	case ch == ',':		return Token{Type: TOKEN_GT, Literal: ">", Pos: start}		}			return Token{Type: TOKEN_GTE, Literal: ">=", Pos: start}			l.advance()		if l.pos < len(l.input) && l.peek() == '=' {	case ch == '>':		return Token{Type: TOKEN_LT, Literal: "<", Pos: start}		}			return Token{Type: TOKEN_NEQ, Literal: "<>", Pos: start}			l.advance()		if l.pos < len(l.input) && l.peek() == '>' {		}			return Token{Type: TOKEN_LTE, Literal: "<=", Pos: start}			l.advance()		if l.pos < len(l.input) && l.peek() == '=' {	case ch == '<':		return Token{Type: TOKEN_ILLEGAL, Literal: "!", Pos: start}		}			return Token{Type: TOKEN_NEQ, Literal: "!=", Pos: start}			l.advance()		if l.pos < len(l.input) && l.peek() == '=' {	case ch == '!':		return Token{Type: TOKEN_EQ, Literal: "=", Pos: start}	case ch == '=':		return l.readNumber(start)	case unicode.IsDigit(ch) || (ch == '-' && l.pos < len(l.input) && unicode.IsDigit(l.peek())):		return l.readIdent(start)	case unicode.IsLetter(ch) || ch == '_':		return l.readString(start)	case ch == '\'':	switch {	ch := l.advance()	start := l.pos	}		return Token{Type: TOKEN_EOF, Pos: l.pos}	if l.pos >= len(l.input) {	l.skipWhitespace()func (l *Lexer) NextToken() Token {// NextToken returns the next token from the input.}	}		l.pos++	for l.pos < len(l.input) && unicode.IsSpace(l.input[l.pos]) {func (l *Lexer) skipWhitespace() {}	return ch	l.pos++	ch := l.input[l.pos]func (l *Lexer) advance() rune {}	return l.input[l.pos]	}		return 0	if l.pos >= len(l.input) {func (l *Lexer) peek() rune {}	return &Lexer{input: []rune(input)}func NewLexer(input string) *Lexer {// NewLexer creates a Lexer for the given input.}	pos   int	input []runetype Lexer struct {// Lexer turns a query string into a stream of Tokens.// -----------------------------------------------------------------------// Lexer// -----------------------------------------------------------------------}	return fmt.Sprintf("Token{%d, %q}", t.Type, t.Literal)func (t Token) String() string {}	Pos     int    // byte offset in source	Literal string // raw text	Type    TokenTypetype Token struct {// Token is a single lexical unit.}	"WITHIN":   TOKEN_WITHIN,	"NEAR":     TOKEN_NEAR,	"CONTAINS": TOKEN_CONTAINS,	"VALUES":   TOKEN_VALUES,	"LIMIT":    TOKEN_LIMIT,	"DESC":     TOKEN_DESC,	"ASC":      TOKEN_ASC,	"BY":       TOKEN_BY,	"ORDER":    TOKEN_ORDER,	"BETWEEN":  TOKEN_BETWEEN,	"NOT":      TOKEN_NOT,	"OR":       TOKEN_OR,	"AND":      TOKEN_AND,	"WHERE":    TOKEN_WHERE,	"FROM":     TOKEN_FROM,	"DELETE":   TOKEN_DELETE,	"SET":      TOKEN_SET,	"UPDATE":   TOKEN_UPDATE,	"INTO":     TOKEN_INTO,	"INSERT":   TOKEN_INSERT,	"SELECT":   TOKEN_SELECT,var keywords = map[string]TokenType{)	TOKEN_ILLEGAL	TOKEN_EOF	TOKEN_STAR // *	TOKEN_RPAREN	TOKEN_LPAREN	TOKEN_COMMA // ,	TOKEN_GTE   // >=	TOKEN_GT    // >	TOKEN_LTE   // <=	TOKEN_LT    // <	TOKEN_NEQ   // !=  <>	TOKEN_EQ    // =	// Operators / punctuation	TOKEN_WITHIN   // spatial bounding box	TOKEN_NEAR     // spatial proximity	TOKEN_CONTAINS // full-text predicate	TOKEN_VALUES	TOKEN_LIMIT	TOKEN_DESC	TOKEN_ASC	TOKEN_BY	TOKEN_ORDER	TOKEN_BETWEEN	TOKEN_NOT	TOKEN_OR	TOKEN_AND	TOKEN_WHERE	TOKEN_FROM	TOKEN_DELETE	TOKEN_SET	TOKEN_UPDATE	TOKEN_INTO	TOKEN_INSERT	TOKEN_SELECT	// Keywords	TOKEN_NUMBER                  // integer or float literal	TOKEN_STRING                  // single-quoted string literal	TOKEN_IDENT  TokenType = iota // unquoted identifier	// Literalsconst (type TokenType int// TokenType categorises a lexical token.// -----------------------------------------------------------------------// Token types// -----------------------------------------------------------------------)	"unicode"	"strings"	"strconv"	"fmt"import (package parser//	WITHIN(minLat, minLon, maxLat, maxLon)  -- bounding-box//	NEAR(lat, lon, radiusMetres)     -- spatial proximity//	CONTAINS(field, 'text')          -- full-text / inverted-index search//	key BETWEEN 'a' AND 'b'//	key = 'x'//// Predicates:////	UPDATE <index> SET value = 'v' WHERE key = 'k'//	DELETE FROM <index> WHERE key = 'k'//	INSERT INTO <index> (key, value) VALUES ('k', 'v')